import type { Locale } from "@/lib/i18n";

// "영화, 한 프레임" — learn composition, light and color from cinema.
//
// Two kinds, split by copyright:
//  - CINEMA_PD: public-domain films (early cinema + 1940s noir whose copyright
//    lapsed). We host the real frame (hotlinked from Wikimedia Commons).
//  - CINEMA_MODERN: in-copyright modern masterpieces, included as a 인용
//    (quotation for criticism/education, 저작권법 §28/§35-5): a single low-res
//    still with full attribution (director + studio) and the educational note
//    that is the whole point. The `studio` credit is mandatory; `image` is
//    filled from a sourced low-res still (left undefined until sourced — the
//    UI hides any modern entry without one rather than render a broken card).
export interface CinemaScene {
  id: string;
  title: Record<Locale, string>;
  credit: Record<Locale, string>; // director (· cinematographer) · year
  lesson: Record<Locale, string>; // what to learn — composition / light / colour
  url: string; // link out (Wikipedia)
  image?: string; // hero still — PD Commons frame, or sourced 인용 still
  gallery?: string[]; // extra stills for the detail page (modern: TMDB low-res)
  curation?: Record<Locale, string>; // longer detail-page description
  studio?: string; // attribution for in-copyright modern stills (required there)
}

export const CINEMA_PD: CinemaScene[] = [
  {
    id: "trip-to-the-moon",
    title: { ko: "달세계 여행", en: "A Trip to the Moon", ja: "月世界旅行" },
    credit: { ko: "조르주 멜리에스 · 1902", en: "Georges Méliès · 1902", ja: "ジョルジュ・メリエス · 1902" },
    lesson: {
      ko: "영화 특수효과의 시대를 연 멜리에스는 무대를 정면으로 바라보는 회화적 구성으로 환상을 빚었습니다. 깊이 없는 평면 무대와 좌우 대칭이 오히려 동화 같은 비현실감을 만듭니다.",
      en: "Méliès, who opened the age of movie special effects, built fantasy with painterly, head-on staging. The flat, frontal set and symmetry are exactly what make it feel like a fairy tale.",
      ja: "映画特殊効果の時代を開いたメリエスは、舞台を正面から捉える絵画的な構図で幻想を作りました。奥行きのない平面的な舞台と左右対称が、むしろ童話のような非現実感を生みます。",
    },
    url: "https://en.wikipedia.org/wiki/A_Trip_to_the_Moon",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Trip_to_the_Moon_Workshop.png/960px-Trip_to_the_Moon_Workshop.png",
  },
  {
    id: "caligari",
    title: { ko: "칼리가리 박사의 밀실", en: "The Cabinet of Dr. Caligari", ja: "カリガリ博士" },
    credit: { ko: "로베르트 비네 · 1920", en: "Robert Wiene · 1920", ja: "ローベルト・ヴィーネ · 1920" },
    lesson: {
      ko: "독일 표현주의의 출발점. 직선이 사라진 사선과 뾰족한 세트, 붓으로 칠한 그림자가 인물의 불안한 내면을 공간 그 자체로 번역합니다.",
      en: "The starting point of German Expressionism. Jagged diagonals, pointed sets and shadows literally painted on the walls translate a disturbed mind into space itself.",
      ja: "ドイツ表現主義の出発点。直線を失った斜線と尖ったセット、筆で描かれた影が、不安な内面を空間そのものに翻訳します。",
    },
    url: "https://en.wikipedia.org/wiki/The_Cabinet_of_Dr._Caligari",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Publicity_still_for_The_Cabinet_of_Dr._Caligari_%281920%29_04.jpg/960px-Publicity_still_for_The_Cabinet_of_Dr._Caligari_%281920%29_04.jpg",
  },
  {
    id: "potemkin",
    title: { ko: "전함 포템킨 (오데사 계단)", en: "Battleship Potemkin (Odessa Steps)", ja: "戦艦ポチョムキン" },
    credit: { ko: "세르게이 에이젠슈테인 · 1925", en: "Sergei Eisenstein · 1925", ja: "セルゲイ・エイゼンシュテイン · 1925" },
    lesson: {
      ko: "몽타주의 정수. 계단을 굴러 내려가는 유모차라는 단 하나의 디테일에 학살의 공포를 응축해, 편집의 리듬이 곧 감정임을 보여줍니다.",
      en: "The essence of montage. The single detail of a pram rolling down the steps concentrates the horror of a massacre — proving that the rhythm of editing is itself emotion.",
      ja: "モンタージュの真髄。階段を転がり落ちる乳母車という一つのディテールに虐殺の恐怖を凝縮し、編集のリズムこそが感情であることを示します。",
    },
    url: "https://en.wikipedia.org/wiki/Battleship_Potemkin",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Odessastepsbaby.jpg",
  },
  {
    id: "phantom-of-the-opera",
    title: { ko: "오페라의 유령", en: "The Phantom of the Opera", ja: "オペラの怪人" },
    credit: { ko: "루퍼트 줄리안 · 1925", en: "Rupert Julian · 1925", ja: "ルパート・ジュリアン · 1925" },
    lesson: {
      ko: "가면이 벗겨지는 순간을 연극적 조명과 실루엣으로 구성합니다. 빛과 어둠의 대비만으로 공포의 절정을 만드는 무성영화 조명의 교본입니다.",
      en: "The unmasking is built from theatrical light and silhouette. A textbook of silent-era lighting that reaches the peak of horror through contrast of light and dark alone.",
      ja: "仮面が剥がれる瞬間を、演劇的な照明とシルエットで構成します。光と闇の対比だけで恐怖の頂点を作る、無声映画照明の教本です。",
    },
    url: "https://en.wikipedia.org/wiki/The_Phantom_of_the_Opera_(1925_film)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Phantomunmasking.jpg/960px-Phantomunmasking.jpg",
  },
  {
    id: "the-general",
    title: { ko: "제너럴", en: "The General", ja: "キートンの大列車追跡" },
    credit: { ko: "버스터 키튼 · 1926", en: "Buster Keaton · 1926", ja: "バスター・キートン · 1926" },
    lesson: {
      ko: "키튼은 기차와 인물, 풍경을 한 프레임 깊숙이 배치(딥 스테이징)해, 컷 없이도 액션의 지리와 인과를 또렷이 읽히게 합니다.",
      en: "Keaton stacks train, figure and landscape deep within one frame (deep staging), so the geography and cause-and-effect of the action read clearly without a single cut.",
      ja: "キートンは列車・人物・風景を一つのフレームの奥深くに配置（ディープ・ステージング）し、カットなしでアクションの地理と因果をはっきり読ませます。",
    },
    url: "https://en.wikipedia.org/wiki/The_General_(1926_film)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/The_General_17.jpg/960px-The_General_17.jpg",
  },
  {
    id: "metropolis",
    title: { ko: "메트로폴리스", en: "Metropolis", ja: "メトロポリス" },
    credit: { ko: "프리츠 랑 · 1927", en: "Fritz Lang · 1927", ja: "フリッツ・ラング · 1927" },
    lesson: {
      ko: "프리츠 랑은 좌우 대칭과 기하학적 군중 배치로 거대 도시의 위압을 시각화합니다. 인간을 하나의 패턴으로 환원하는 구도가 곧 주제가 됩니다.",
      en: "Fritz Lang visualises the menace of the mega-city through symmetry and geometric crowds. The composition that reduces humans to a pattern is itself the theme.",
      ja: "フリッツ・ラングは左右対称と幾何学的な群衆配置で巨大都市の威圧を視覚化します。人間を一つのパターンに還元する構図こそがテーマです。",
    },
    url: "https://en.wikipedia.org/wiki/Metropolis_(1927_film)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Metropolis_%281927%29_-_Hel.jpg/960px-Metropolis_%281927%29_-_Hel.jpg",
  },
  {
    id: "man-with-a-movie-camera",
    title: { ko: "카메라를 든 사나이", en: "Man with a Movie Camera", ja: "カメラを持った男" },
    credit: { ko: "지가 베르토프 · 1929", en: "Dziga Vertov · 1929", ja: "ジガ・ヴェルトフ · 1929" },
    lesson: {
      ko: "베르토프는 이중노출과 '카메라를 찍는 카메라'로 영화가 스스로를 드러내게 합니다. 구도 자체가 보는 행위에 대한 질문이 됩니다.",
      en: "Vertov makes cinema reveal itself through double exposure and a camera filming the camera. The composition itself becomes a question about the act of seeing.",
      ja: "ヴェルトフは二重露光と「カメラを撮るカメラ」で、映画自身を露わにします。構図そのものが「見る」という行為への問いになります。",
    },
    url: "https://en.wikipedia.org/wiki/Man_with_a_Movie_Camera",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Man_with_a_Movie_Camera_by_Dziga_Vertov.jpg",
  },
  {
    id: "detour",
    title: { ko: "디투어", en: "Detour", ja: "恐怖のまわり道" },
    credit: { ko: "에드거 G. 울머 · 1945", en: "Edgar G. Ulmer · 1945", ja: "エドガー・G・ウルマー · 1945" },
    lesson: {
      ko: "저예산 누아르의 전설. 최소한의 저조도 조명과 좁은 프레임이 인물을 운명에 가두는 폐소감을 만듭니다.",
      en: "A legend of low-budget noir. Minimal low-key lighting and a tight frame create the claustrophobia of a man trapped by fate.",
      ja: "低予算ノワールの伝説。最小限のローキー照明と狭いフレームが、運命に囚われた人物の閉塞感を生みます。",
    },
    url: "https://en.wikipedia.org/wiki/Detour_(1945_film)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Ann_Savage_and_Tom_Neal_in_Detour.jpg/960px-Ann_Savage_and_Tom_Neal_in_Detour.jpg",
  },
  {
    id: "scarlet-street",
    title: { ko: "스칼렛 스트리트", en: "Scarlet Street", ja: "スカーレット・ストリート" },
    credit: { ko: "프리츠 랑 · 1945", en: "Fritz Lang · 1945", ja: "フリッツ・ラング · 1945" },
    lesson: {
      ko: "프리츠 랑이 누아르로 옮긴 그림자. 인물을 어둠 속에 고립시키는 조명이 욕망과 파멸의 심리를 공간으로 그립니다.",
      en: "The shadow Fritz Lang carried into noir. Lighting that isolates a figure in darkness draws the psychology of desire and ruin as space.",
      ja: "フリッツ・ラングがノワールに持ち込んだ影。人物を闇の中に孤立させる照明が、欲望と破滅の心理を空間として描きます。",
    },
    url: "https://en.wikipedia.org/wiki/Scarlet_Street",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Joan_Bennett_in_Scarlet_Street_%282%29.jpg/960px-Joan_Bennett_in_Scarlet_Street_%282%29.jpg",
  },
  {
    id: "the-stranger",
    title: { ko: "이방인", en: "The Stranger", ja: "上海から来た女… (The Stranger)" },
    credit: { ko: "오슨 웰스 · 1946", en: "Orson Welles · 1946", ja: "オーソン・ウェルズ · 1946" },
    lesson: {
      ko: "오슨 웰스 특유의 깊은 공간과 강한 명암 대비. 전경과 후경을 동시에 또렷이 살리는 구성이 긴장을 끌어올립니다.",
      en: "Orson Welles's signature deep space and hard chiaroscuro. Keeping foreground and background both in sharp focus ratchets up the tension.",
      ja: "オーソン・ウェルズ特有の深い空間と強い明暗対比。前景と後景を同時にくっきり捉える構図が緊張を高めます。",
    },
    url: "https://en.wikipedia.org/wiki/The_Stranger_(1946_film)",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/The_Stranger_1946_%283%29.jpg",
  },
];

export const CINEMA_MODERN: CinemaScene[] = [
  {
    id: "in-the-mood-for-love",
    title: { ko: "화양연화", en: "In the Mood for Love", ja: "花様年華" },
    credit: { ko: "왕가위 · 촬영 크리스토퍼 도일, 리핑빈 · 2000", en: "Dir. Wong Kar-wai · DP Christopher Doyle, Lee Ping-bin · 2000", ja: "監督 ウォン・カーウァイ · 撮影 クリストファー・ドイル、リー・ピンビン · 2000" },
    lesson: { ko: "포화된 빨강과 초록, 그리고 좁은 프레임이 어떻게 억눌린 감정을 화면에 새기는지 배워 보세요. 색은 분위기가 아니라 인물의 마음입니다.", en: "Learn how saturated reds and greens, locked inside cramped frames, etch suppressed emotion onto the image. Here colour isn't mood — it's the characters' hearts.", ja: "飽和した赤と緑、そして狭いフレームが、いかに抑えた感情を画面に刻むかを学べます。色は雰囲気ではなく、人物の心そのものです。" },
    curation: { ko: "왕가위와 두 촬영감독 크리스토퍼 도일, 리핑빈은 1960년대 홍콩의 비좁은 복도와 셋방을 짙은 빨강과 초록으로 물들여, 닿지 못하는 두 사람의 거리를 색과 공간으로 번역해 냈습니다. 문틀과 거울, 커튼 같은 전경 요소로 인물을 가두듯 프레임을 좁히고, 치파오의 무늬가 바뀔 때마다 시간과 감정의 결이 함께 흐릅니다. 슬로모션과 반복되는 동선은 일상의 스침을 의식처럼 격상시키죠. 구도가 어떻게 절제된 감정을 담는 그릇이 되는지, 이 영화만큼 우아하게 보여 주는 예는 드뭅니다.", en: "Wong Kar-wai and his two cinematographers, Christopher Doyle and Lee Ping-bin, soak the narrow corridors and rented rooms of 1960s Hong Kong in deep red and green, translating the unbridgeable distance between two people into colour and space. Doorframes, mirrors and curtains crowd the foreground, boxing the lovers in, while each change of cheongsam pattern marks the passing of time and feeling. Slow motion and repeated movements raise everyday brushes-past to the level of ritual. Few films show so gracefully how framing becomes a vessel for restrained emotion.", ja: "ウォン・カーウァイと二人の撮影監督クリストファー・ドイル、リー・ピンビンは、1960年代香港の狭い廊下や間借り部屋を濃い赤と緑で染め上げ、結ばれない二人の距離を色と空間に翻訳しました。ドア枠や鏡、カーテンといった前景の要素が人物を囲い込むようにフレームを狭め、チャイナドレスの柄が変わるたびに時間と感情の移ろいが流れていきます。スローモーションと反復する動線は、日常のすれ違いを儀式のように高めます。構図がいかに抑制された感情の器となるか、これほど優雅に示す作品は稀です。" },
    url: "https://www.themoviedb.org/movie/843",
    image: "https://image.tmdb.org/t/p/w780/2USUGY484L6sUkjeD1Y0rG8uRC9.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/2USUGY484L6sUkjeD1Y0rG8uRC9.jpg", "https://image.tmdb.org/t/p/w780/ffQFnAUm2Uu4RU0nijpjPRf9TBT.jpg", "https://image.tmdb.org/t/p/w780/4JevqhhdW38aOUjCvSUDx568Ty2.jpg", "https://image.tmdb.org/t/p/w780/n4GJFGzsc7NinI1VeGDXIcQjtU2.jpg"],
    studio: "Block 2 Pictures · Paradis Films",
  },
  {
    id: "chungking-express",
    title: { ko: "중경삼림", en: "Chungking Express", ja: "恋する惑星" },
    credit: { ko: "왕가위 · 촬영 크리스토퍼 도일 · 1994", en: "Dir. Wong Kar-wai · DP Christopher Doyle · 1994", ja: "監督 ウォン・カーウァイ · 撮影 クリストファー・ドイル · 1994" },
    lesson: { ko: "흐릿하게 번지는 네온과 스텝 프린팅이 만든 모션 블러로, 한 도시의 외로움을 색과 속도감으로 옮기는 법을 배웁니다.", en: "Learn how smeared neon and step-printed motion blur translate a city's loneliness into colour and the feeling of speed.", ja: "にじむネオンとステップ・プリントのブレから、都市の孤独を色とスピード感へ翻訳する術を学びます。" },
    curation: { ko: "도일은 흔들리는 핸드헬드와 좁은 화각으로 홍콩의 좁은 거리와 패스트푸드점을 끈적한 색면으로 채웁니다. 셔터 속도를 늦춰 프레임을 솎아내는 스텝 프린팅 기법은 행인은 흐르게 두고 주인공만 또렷이 남겨, 군중 속 고립을 시각화합니다. 형광등 초록과 네온 주황이 보색으로 부딪히며 화면에 도시 특유의 피로와 설렘을 동시에 입힙니다. 빛이 흐트러진 자리에서 감정을 길어 올리는 방식을 공부하기에 더없이 좋은 작품입니다.", en: "With restless handheld camera and tight framing, Doyle fills Hong Kong's narrow streets and fast-food stalls with sticky slabs of colour. The step-printing technique, which thins out frames to slow the shutter, lets passers-by blur while keeping the protagonist sharp, making isolation within a crowd visible. Fluorescent green and neon orange clash as complementary colours, lending the image both the fatigue and the flutter peculiar to the city. It is an ideal film for studying how emotion can be drawn from light left deliberately unsettled.", ja: "ドイルは揺れるハンドヘルドと狭い画角で、香港の細い路地やファストフード店を粘りつくような色面で満たします。シャッター速度を落としてコマを間引くステップ・プリント技法は、通行人をブレさせ主人公だけを際立たせ、群衆の中の孤立を可視化します。蛍光灯の緑とネオンの橙が補色としてぶつかり合い、画面に都市特有の疲れと高揚を同時にまといます。あえて乱した光から感情を汲み上げる方法を学ぶのに、これ以上ない一本です。" },
    url: "https://www.themoviedb.org/movie/11104",
    image: "https://image.tmdb.org/t/p/w780/i4m14DMv0JG4AOH6sP7Pes87A9x.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/i4m14DMv0JG4AOH6sP7Pes87A9x.jpg", "https://image.tmdb.org/t/p/w780/hqyA3dCWdc0cCH2Ba8ZhZTjDA8y.jpg", "https://image.tmdb.org/t/p/w780/vuglA60RqvpHK9rIcG8sXaiWw1L.jpg", "https://image.tmdb.org/t/p/w780/zToFuGe2hV3XuTDQLCAsQqmWoWk.jpg"],
    studio: "Jet Tone Production",
  },
  {
    id: "fallen-angels",
    title: { ko: "타락천사", en: "Fallen Angels", ja: "天使の涙" },
    credit: { ko: "왕가위 · 촬영 크리스토퍼 도일 · 1995", en: "Wong Kar-wai · DP Christopher Doyle · 1995", ja: "ウォン・カーウァイ · 撮影 クリストファー・ドイル · 1995" },
    lesson: { ko: "초광각 렌즈가 만드는 왜곡과 거리감을 배워보세요. 같은 프레임 안에 있어도 인물들이 서로 닿지 못하는 고독을 화면 형태 자체로 말하는 법을 보여줍니다.", en: "Study how an extreme wide-angle lens warps space into loneliness. Even when two people share the frame, the bent geometry keeps them apart.", ja: "超広角レンズが生む歪みと距離感を学べます。同じフレームにいても触れ合えない孤独を、画面の形そのもので語る手法です。" },
    curation: { ko: "크리스토퍼 도일은 초광각 렌즈를 인물에 바짝 들이대 홍콩의 밤을 휘어진 거울처럼 비틉니다. 네온의 붉고 푸른 빛이 번지는 좁은 공간 속에서 얼굴은 가까이 있어도 멀어 보이고, 그 왜곡이 곧 외로움의 형태가 됩니다. 핸드헬드와 스텝 프린팅으로 흐려진 시간감은 도시의 새벽을 꿈처럼 만들죠. 빛과 렌즈만으로 정서를 만드는 법을 배우고 싶다면 한 컷 한 컷을 천천히 들여다볼 가치가 있는 작품입니다.", en: "Christopher Doyle pushes a wide-angle lens right up against his characters, bending Hong Kong's night into a funhouse mirror. In cramped neon-soaked rooms, faces that sit close suddenly feel far away, and that distortion becomes the very shape of isolation. Handheld energy and step-printing smear time until the city's small hours feel like a dream. If you want to learn how light and lens alone can carry emotion, this film rewards frame-by-frame attention.", ja: "クリストファー・ドイルは超広角レンズを人物に極端に近づけ、香港の夜を歪んだ鏡のように曲げます。ネオンの赤と青がにじむ狭い空間では、近くにいる顔さえ遠く見え、その歪みがそのまま孤独の形になります。手持ちの揺れとステップ・プリンティングが時間感覚をぼかし、都市の未明を夢のように変えます。光とレンズだけで感情を生む術を学びたいなら、一カットずつじっくり見る価値のある一作です。" },
    url: "https://www.themoviedb.org/movie/11220",
    image: "https://image.tmdb.org/t/p/w780/lInQVVbPjKFGX7GDcxNMXALy2Y4.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/lInQVVbPjKFGX7GDcxNMXALy2Y4.jpg", "https://image.tmdb.org/t/p/w780/uPc5yPNmEZmDg21WOWk4deYzK2L.jpg", "https://image.tmdb.org/t/p/w780/i4bbJnECdbgb7o12NyHnJa5MUIu.jpg", "https://image.tmdb.org/t/p/w780/v4FepSc09TsRy2fQtUg6vvzrTq0.jpg"],
    studio: "Jet Tone Production",
  },
  {
    id: "2046",
    title: { ko: "2046", en: "2046", ja: "2046" },
    credit: { ko: "왕가위 · 촬영 크리스토퍼 도일, 콴 푼렁, 리핑빙 · 2004", en: "Wong Kar-wai · DP Christopher Doyle, Kwan Pun-leung, Lee Ping-bin · 2004", ja: "ウォン・カーウァイ · 撮影 クリストファー・ドイル、コアン・プンリョン、リー・ピンビン · 2004" },
    lesson: { ko: "포화된 색으로 기억과 감정을 칠하는 법을 배워보세요. 붉은 커튼과 푸른 그림자가 화면을 정서로 물들입니다.", en: "Learn to paint memory and emotion with saturated colour, where red drapes and blue shadows soak the frame in feeling.", ja: "飽和した色で記憶と感情を塗る術を学べます。赤いカーテンと青い影が画面を情緒で染め上げます。" },
    curation: { ko: "왕가위와 세 촬영감독은 짙고 관능적인 색채로 시간과 기억의 미로를 빚어냅니다. 좁은 프레임과 흐릿한 전경, 느린 셔터의 잔상이 인물을 과거에 가두고, 미래로 향하는 열차는 차가운 청록으로 분리됩니다. 한 장면 안에서도 따뜻한 호박색과 서늘한 푸른빛이 끊임없이 부딪치며 욕망과 상실을 동시에 말합니다. 색이 어떻게 서사가 되는지를 가장 우아하게 보여주는 작품입니다.", en: "Wong Kar-wai and his three cinematographers sculpt a labyrinth of time and memory in dense, sensual colour. Cramped frames, soft foregrounds and smeared slow-shutter trails trap the characters in the past, while the train to the future is set apart in cold teal. Within a single shot warm amber and cool blue keep colliding, speaking of desire and loss at once. It is one of the most elegant demonstrations of how colour itself becomes narrative.", ja: "ウォン・カーウァイと三人の撮影監督が、濃密で官能的な色彩で時間と記憶の迷宮を彫り上げます。狭いフレーム、ぼけた前景、スローシャッターの残像が人物を過去に閉じ込め、未来へ向かう列車は冷たい青緑で切り離されます。一つのショットの中でも温かい琥珀色と冷たい青が衝突し続け、欲望と喪失を同時に語ります。色がいかに物語そのものになるかを、最も優雅に示す一本です。" },
    url: "https://www.themoviedb.org/movie/844",
    image: "https://image.tmdb.org/t/p/w780/h3JAMIeywbzobkhu2rt3mQAwRR1.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/h3JAMIeywbzobkhu2rt3mQAwRR1.jpg", "https://image.tmdb.org/t/p/w780/uUsatXPThHrUSvdB6fg4782p0Cd.jpg", "https://image.tmdb.org/t/p/w780/yu81JgyhfrilG6Ax0ajnh8utuPc.jpg", "https://image.tmdb.org/t/p/w780/bpveJQCyjNJtMFilQAxzTmJfrz6.jpg"],
    studio: "Shanghai Film Group · Orly Films",
  },
  {
    id: "hero",
    title: { ko: "영웅", en: "Hero", ja: "HERO 英雄" },
    credit: { ko: "장이머우 · 촬영 크리스토퍼 도일 · 2002", en: "Dir. Zhang Yimou · DP Christopher Doyle · 2002", ja: "監督 チャン・イーモウ · 撮影 クリストファー・ドイル · 2002" },
    lesson: { ko: "하나의 장(章)을 하나의 색으로 통일해, 색 자체가 이야기와 시점을 구분하게 만드는 방식을 배워 보세요. 색은 챕터의 감정 키입니다.", en: "Learn how each chapter is unified under a single dominant colour, so that colour itself separates story and point of view. Hue becomes the emotional key of each act.", ja: "一つの章を一つの色で統一し、色そのものが物語や視点を分ける手法を学べます。色彩は各章の感情のキーになります。" },
    curation: { ko: "장이머우와 촬영감독 크리스토퍼 도일은 같은 사건을 여러 번 다시 들려주면서, 그 버전마다 화면 전체를 빨강·파랑·하양·초록 한 가지 색으로 물들였습니다. 의상과 휘날리는 천, 가을 숲의 잎까지 색조를 맞춰, 색이 진실과 거짓, 기억과 욕망을 구분하는 문법으로 작동하죠. 바람에 흩날리는 직물과 느려진 무술 안무는 색면을 캔버스처럼 펼쳐 보입니다. 색채 하나로 서사를 설계하는 법을 공부하고 싶다면 더없이 좋은 교과서입니다.", en: "Zhang Yimou and cinematographer Christopher Doyle retell the same events several times, drenching each version of the screen in a single colour — red, blue, white, green. Costumes, billowing fabric, even the leaves of an autumn forest are tuned to the palette, so that colour becomes a grammar for separating truth from lie, memory from desire. Wind-tossed cloth and slowed martial choreography spread each colour field out like a canvas. As a lesson in designing narrative through hue alone, it is hard to beat.", ja: "チャン・イーモウと撮影監督クリストファー・ドイルは同じ事件を何度も語り直し、そのたびに画面全体を赤・青・白・緑のひとつの色で染め上げます。衣装や翻る布、秋の森の葉まで色調を揃え、色が真実と虚偽、記憶と欲望を分ける文法として機能します。風になびく織物とスローになった武術の所作が、色面をカンバスのように広げて見せます。色彩ひとつで物語を設計する術を学ぶなら、これ以上ない手本です。" },
    url: "https://www.themoviedb.org/movie/79",
    image: "https://image.tmdb.org/t/p/w780/jDz6RYN3nKYtlo7J9IMvGoJit7B.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/jDz6RYN3nKYtlo7J9IMvGoJit7B.jpg", "https://image.tmdb.org/t/p/w780/5cWwxxEj6B5ZvlnsfGbXd7pfkXd.jpg", "https://image.tmdb.org/t/p/w780/zwhlcTqHkD3d4LEvjJwRc9Ixyl2.jpg"],
    studio: "Beijing New Picture Film Co. Ltd. · China Film Co-Production",
  },
  {
    id: "raise-the-red-lantern",
    title: { ko: "홍등", en: "Raise the Red Lantern", ja: "紅夢" },
    credit: { ko: "장이머우 · 촬영 자오페이 · 1991", en: "Dir. Zhang Yimou · DP Zhao Fei · 1991", ja: "監督 チャン・イーモウ · 撮影 チャオ・フェイ · 1991" },
    lesson: { ko: "붉은 등롱과 좌우 대칭의 회랑 구도로, 색 하나와 엄격한 프레임만으로 인물을 가두는 법을 배웁니다.", en: "Learn how a single red and rigidly symmetrical framing can imprison a character within the image.", ja: "紅い提灯と左右対称の構図から、ひと色と厳格なフレームだけで人物を閉じ込める術を学びます。" },
    curation: { ko: "장이머우와 자오페이는 사합원의 회랑과 처마를 정면 대칭으로 잡아, 인물을 건축의 격자 속에 박아 넣습니다. 화면을 지배하는 붉은 등롱은 욕망과 권력, 동시에 구속을 뜻하며 회색 담장과 강렬한 보색으로 부딪힙니다. 카메라는 좀처럼 움직이지 않고 멀찍이 물러서서, 한 여인이 규율의 미로 안에서 점점 작아지는 모습을 관조합니다. 색과 대칭이 어떻게 곧장 감옥의 은유가 되는지 보여 주는 교과서 같은 화면입니다.", en: "Zhang Yimou and Zhao Fei frame the courtyard compound's corridors and eaves in head-on symmetry, pinning their characters into a grid of architecture. The red lanterns that dominate the image stand for desire and power and at once for confinement, clashing as a vivid complement against the grey walls. The camera rarely moves and keeps its distance, contemplating a woman who grows ever smaller inside a maze of discipline. It is a textbook image of how colour and symmetry become, directly, a metaphor for prison.", ja: "チャン・イーモウとチャオ・フェイは四合院の回廊や軒を正面対称でとらえ、人物を建築の格子の中に嵌め込みます。画面を支配する紅い提灯は欲望と権力を、同時に束縛を意味し、灰色の塀と鮮烈な補色としてぶつかります。カメラはほとんど動かず遠くから引き、規律の迷路の中で次第に小さくなっていく一人の女を見つめます。色と対称がいかにそのまま牢獄の隠喩となるかを示す、教科書のような画です。" },
    url: "https://www.themoviedb.org/movie/10404",
    image: "https://image.tmdb.org/t/p/w780/7aRdT0ijJdME6jY8PzHgzAmw0dd.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/7aRdT0ijJdME6jY8PzHgzAmw0dd.jpg", "https://image.tmdb.org/t/p/w780/9UCHfC9tYojD4mMVBm0boyzYEQq.jpg", "https://image.tmdb.org/t/p/w780/625WbFVPzq2eju0I62TMljD15dQ.jpg", "https://image.tmdb.org/t/p/w780/wirTKOfARbjq2NsSFA3MHeQaHil.jpg"],
    studio: "ERA International · China Film Co-Production",
  },
  {
    id: "house-of-flying-daggers",
    title: { ko: "연인", en: "House of Flying Daggers", ja: "LOVERS" },
    credit: { ko: "장이머우 · 촬영 자오샤오딩 · 2004", en: "Zhang Yimou · DP Zhao Xiaoding · 2004", ja: "チャン・イーモウ · 撮影 チャオ・シャオティン · 2004" },
    lesson: { ko: "한 가지 색으로 화면 전체를 물들이는 색채 연출을 배워보세요. 초록 대나무 숲, 황금 들판처럼 단일 색으로 통일된 공간이 감정의 온도를 어떻게 끌어올리는지 보여줍니다.", en: "Learn how flooding a frame with a single colour sets its emotional temperature. From the green bamboo grove to golden fields, each space is tuned to one dominant hue.", ja: "一つの色で画面全体を染める色彩演出を学べます。緑の竹林や黄金の野原のように、単色で統一された空間が感情の温度をどう高めるかがわかります。" },
    curation: { ko: "장이머우와 자오샤오딩은 색을 무대 조명처럼 다룹니다. 끝없이 펼쳐진 초록 대나무 숲, 가을빛 황금 들판, 새하얀 눈밭으로 이어지는 계절의 변화는 그 자체로 감정의 곡선을 그립니다. 메아리 게임 시퀀스에서 보듯 동작과 소리, 색이 정교하게 맞물려 액션을 한 폭의 그림으로 끌어올리죠. 채도 높은 단색 공간이 어떻게 화면의 정서를 지배하는지, 색채 연출의 교과서로 삼을 만한 작품입니다.", en: "Zhang Yimou and Zhao Xiaoding treat colour like stage lighting. The sweep from an endless green bamboo forest to autumn-gold fields and pure white snow draws an emotional arc all by itself. As the famous echo-game sequence shows, movement, sound and colour lock together to lift the action into something painterly. As a primer on how a single saturated hue can govern the mood of a frame, this film is a textbook.", ja: "チャン・イーモウとチャオ・シャオティンは色を舞台照明のように扱います。果てしない緑の竹林から、秋の黄金の野原、純白の雪原へと移る季節の変化が、それ自体で感情の曲線を描きます。名高い反響の遊びの場面が示すように、動きと音と色が緻密に噛み合い、アクションを一幅の絵へと高めます。彩度の高い単色空間が画面の情緒をいかに支配するか、色彩演出の教科書とすべき一作です。" },
    url: "https://www.themoviedb.org/movie/9550",
    image: "https://image.tmdb.org/t/p/w780/v6LFOcdVZZilv87vrAAoohUN74s.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/v6LFOcdVZZilv87vrAAoohUN74s.jpg", "https://image.tmdb.org/t/p/w780/zCzlM554qU21L90ruXhGcuURTLi.jpg", "https://image.tmdb.org/t/p/w780/jea4adbYk407PhYK9uhWjihPYAv.jpg", "https://image.tmdb.org/t/p/w780/s1PR5QMpSlA0rkFn02u88OUCXLN.jpg"],
    studio: "China Film Co-Production · Elite Group Enterprises",
  },
  {
    id: "2001",
    title: { ko: "2001 스페이스 오디세이", en: "2001: A Space Odyssey", ja: "2001年宇宙の旅" },
    credit: { ko: "스탠리 큐브릭 · 촬영 제프리 언스워스 · 1968", en: "Stanley Kubrick · DP Geoffrey Unsworth · 1968", ja: "スタンリー・キューブリック · 撮影 ジェフリー・アンスワース · 1968" },
    lesson: { ko: "완벽한 좌우 대칭과 일점 투시 구도를 배워보세요. 흰색과 검정의 절제 속에서 단 하나의 빨강이 모든 시선을 끌어당깁니다.", en: "Learn perfect symmetry and one-point perspective, where amid white-and-black restraint a single red commands all attention.", ja: "完璧な左右対称と一点透視の構図を学べます。白と黒の抑制の中で、たった一つの赤がすべての視線を引き寄せます。" },
    curation: { ko: "큐브릭과 언스워스는 화면을 기하학으로 다스립니다. 소실점을 중앙에 둔 일점 투시와 좌우 대칭은 우주의 차갑고 거대한 질서를 시각화하고, 흰색과 검정으로 절제된 팔레트는 군더더기를 모두 걷어냅니다. 그 무채색의 정적 속에서 HAL의 붉은 렌즈만이 유일하게 살아 있는 색으로 불안과 의지를 응축합니다. 구도와 색의 절제가 어떻게 압도적인 숭고함을 만드는지 가르쳐 주는 교과서입니다.", en: "Kubrick and Unsworth govern the frame through geometry. Centred one-point perspective and rigorous symmetry visualise the cold, immense order of space, while a palette pared down to white and black strips away every excess. In that achromatic stillness, only HAL's red lens lives as colour, concentrating dread and will into a single point. It is a textbook on how restraint in composition and colour can produce overwhelming sublimity.", ja: "キューブリックとアンスワースは幾何学で画面を統べます。中央に消失点を置く一点透視と厳密な左右対称が宇宙の冷たく巨大な秩序を可視化し、白と黒に切り詰めたパレットが余分をすべてそぎ落とします。その無彩色の静寂の中で、HALの赤いレンズだけが唯一生きた色として、不安と意志を一点に凝縮します。構図と色の抑制がいかに圧倒的な崇高さを生むかを教える教科書です。" },
    url: "https://www.themoviedb.org/movie/62",
    image: "https://image.tmdb.org/t/p/w780/w5IDXtifKntw0ajv2co7jFlTQDM.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/w5IDXtifKntw0ajv2co7jFlTQDM.jpg", "https://image.tmdb.org/t/p/w780/yfnDgz3Kiv0IkdujrFRh1vcd7Yu.jpg", "https://image.tmdb.org/t/p/w780/6gyZF4SeifiUUYDELkCS8nOqsu2.jpg", "https://image.tmdb.org/t/p/w780/spoZUN4X1KiOc5S0plOyGAXLNtb.jpg"],
    studio: "Stanley Kubrick Productions · Metro-Goldwyn-Mayer",
  },
  {
    id: "the-shining",
    title: { ko: "샤이닝", en: "The Shining", ja: "シャイニング" },
    credit: { ko: "스탠리 큐브릭 · 촬영 존 올콧 · 1980", en: "Dir. Stanley Kubrick · DP John Alcott · 1980", ja: "監督 スタンリー・キューブリック · 撮影 ジョン・オルコット · 1980" },
    lesson: { ko: "완벽한 좌우 대칭과 소실점 구도가 어떻게 불안과 공포를 만들어 내는지 배워 보세요. 너무 반듯한 화면은 오히려 섬뜩합니다.", en: "Learn how perfect symmetry and one-point perspective generate unease and dread. A frame too orderly becomes uncanny.", ja: "完璧な左右対称と一点透視の構図が、いかに不安と恐怖を生み出すかを学べます。整いすぎた画面はかえって不気味です。" },
    curation: { ko: "스탠리 큐브릭과 촬영감독 존 올콧은 오버룩 호텔을 중심선이 또렷한 대칭 구도와 끝없이 이어지는 복도로 빚어, 보는 이를 미로 같은 공간 감각에 가둡니다. 막 상용화된 스테디캠으로 카메라가 소년의 세발자전거를 따라 미끄러질 때, 매끈한 움직임이 오히려 발밑이 꺼지는 듯한 공포를 부르죠. 차갑고 균질한 호텔 조명은 일상적인 밝기 속에 위협을 숨겨 둡니다. 질서정연한 구도가 어떻게 가장 깊은 공포의 도구가 되는지 배우기에 더없이 좋은 작품입니다.", en: "Stanley Kubrick and cinematographer John Alcott build the Overlook Hotel out of rigidly symmetrical compositions and endless corridors, trapping the viewer in a maze-like sense of space. As the newly practical Steadicam glides behind the boy's tricycle, the very smoothness of the motion summons a floor-dropping dread. The hotel's cold, even light hides menace inside ordinary brightness. There is no better film for learning how orderly composition can become the deepest instrument of fear.", ja: "スタンリー・キューブリックと撮影監督ジョン・オルコットは、オーバールック・ホテルを厳格な左右対称の構図と果てしなく続く廊下で築き上げ、観る者を迷宮のような空間感覚に閉じ込めます。実用化されたばかりのステディカムが少年の三輪車を追って滑らかに進むとき、その滑らかさこそが足元の崩れるような恐怖を呼びます。冷たく均質なホテルの照明は、日常的な明るさの中に脅威を潜ませます。秩序立った構図がいかに最も深い恐怖の道具となるかを学ぶには、この上ない一本です。" },
    url: "https://www.themoviedb.org/movie/694",
    image: "https://image.tmdb.org/t/p/w780/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg", "https://image.tmdb.org/t/p/w780/lEqwBnJxiLFbjadBcDi2B2FrsDF.jpg", "https://image.tmdb.org/t/p/w780/hWbC1ix65Ln7GySSvt6oe31A9GY.jpg"],
    studio: "Warner Bros. Pictures · Peregrine",
  },
  {
    id: "barry-lyndon",
    title: { ko: "배리 린든", en: "Barry Lyndon", ja: "バリー・リンドン" },
    credit: { ko: "스탠리 큐브릭 · 촬영 존 올컷 · 1975", en: "Dir. Stanley Kubrick · DP John Alcott · 1975", ja: "監督 スタンリー・キューブリック · 撮影 ジョン・オルコット · 1975" },
    lesson: { ko: "촛불만으로 찍어낸 실내와 회화 같은 18세기 화면에서, 인공조명 없이 빛 자체를 다루는 법을 배웁니다.", en: "Learn to work with available light itself from interiors lit by candle flame alone and painterly 18th-century tableaux.", ja: "蝋燭の灯だけで撮られた室内と絵画のような18世紀の画から、人工照明に頼らず光そのものを扱う術を学びます。" },
    curation: { ko: "큐브릭과 올컷은 NASA가 개발한 초고속 렌즈를 영화 카메라에 이식해, 오직 촛불만으로 야간 실내를 노출시켰습니다. 그 결과 화면은 게인즈버러나 호가스의 유화처럼 부드러운 명암과 깊은 어둠을 품게 됩니다. 야외 장면은 자연광을 그대로 받아 한 폭의 풍경화로 구성되고, 인물은 늘 시대의 의상과 건축 안에 정교하게 배치됩니다. 빛을 새로 만드는 대신 있는 빛을 최대한 끌어모으는 태도를 배우기에 가장 좋은 본보기입니다.", en: "Kubrick and Alcott grafted an ultra-fast lens developed for NASA onto a movie camera, exposing night interiors by candle flame alone. The result carries the soft gradations and deep shadow of an oil painting by Gainsborough or Hogarth. Exterior scenes take natural light as it falls, composed like landscape paintings, with figures precisely placed inside period costume and architecture. It is the finest example for learning an attitude that gathers all the available light rather than manufacturing it anew.", ja: "キューブリックとオルコットはNASAが開発した超高速レンズを映画用カメラに移植し、蝋燭の灯だけで夜の室内を露光しました。その結果、画面はゲインズバラやホガースの油彩のような柔らかな階調と深い闇をたたえます。屋外の場面は自然光をそのまま受けて一幅の風景画のように構成され、人物は常に時代の衣装と建築の中に精密に配置されます。光を新たに作るのではなく、ある光を最大限かき集める姿勢を学ぶのに最良の手本です。" },
    url: "https://www.themoviedb.org/movie/3175",
    image: "https://image.tmdb.org/t/p/w780/gIsqckWVb2yKHJ4o78rysl6a34d.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/gIsqckWVb2yKHJ4o78rysl6a34d.jpg", "https://image.tmdb.org/t/p/w780/okdg55jhsr9k1F2lxsZoQncrLZL.jpg", "https://image.tmdb.org/t/p/w780/813JR9exYGSO7P2aphYrkjrOItz.jpg", "https://image.tmdb.org/t/p/w780/s8cVgfxNEIRcTPhZPDfTPVBFdZn.jpg"],
    studio: "Warner Bros. Pictures · Hawk Films",
  },
  {
    id: "grand-budapest-hotel",
    title: { ko: "그랜드 부다페스트 호텔", en: "The Grand Budapest Hotel", ja: "グランド・ブダペスト・ホテル" },
    credit: { ko: "웨스 앤더슨 · 촬영 로버트 예먼 · 2014", en: "Wes Anderson · DP Robert Yeoman · 2014", ja: "ウェス・アンダーソン · 撮影 ロバート・イェオマン · 2014" },
    lesson: { ko: "정중앙 대칭 구도와 파스텔 색팔레트를 배워보세요. 화면 한가운데 피사체를 두고 좌우를 완벽히 맞추는 구성이 어떻게 동화 같은 세계를 만드는지 보여줍니다.", en: "Learn dead-centre symmetry and the pastel palette. Placing a subject in the exact middle and balancing both sides builds a storybook world.", ja: "ど真ん中の対称構図とパステルの色彩設計を学べます。被写体を画面中央に置き左右を完璧に揃える構成が、おとぎ話のような世界をどう作るかがわかります。" },
    curation: { ko: "웨스 앤더슨과 로버트 예먼은 화면을 인형의 집처럼 정밀하게 설계합니다. 피사체를 정중앙에 놓고 좌우를 완벽히 대칭으로 맞춘 구도, 분홍과 보라가 감도는 파스텔 팔레트가 영화 전체를 하나의 디저트처럼 보이게 하죠. 시대마다 화면비를 바꿔 과거와 현재를 구분하는 영리한 선택도 눈여겨볼 만합니다. 구도의 질서가 어떻게 고유한 세계관과 유머를 만드는지, 프레이밍을 공부하기에 더없이 좋은 교본입니다.", en: "Wes Anderson and Robert Yeoman build each shot with dollhouse precision. Subjects sit dead centre, both sides mirrored, while a pastel wash of pink and purple makes the whole film look like a confection. Watch too how the aspect ratio shifts with each era to separate past from present. As a study in how compositional order creates a world and its humour, it is an ideal primer on framing.", ja: "ウェス・アンダーソンとロバート・イェオマンは、各ショットを人形の家のような精密さで組み立てます。被写体を真ん中に置き左右を完璧に対称にした構図、ピンクと紫がかったパステルの色彩が、映画全体を一つのお菓子のように見せます。時代ごとに画面比を変え、過去と現在を分ける巧みな選択にも注目です。構図の秩序がいかに独自の世界観とユーモアを生むか、フレーミングを学ぶ格好の手本です。" },
    url: "https://www.themoviedb.org/movie/120467",
    image: "https://image.tmdb.org/t/p/w780/9udCLTxTFl28RxnK8Q05E154ZGa.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/9udCLTxTFl28RxnK8Q05E154ZGa.jpg", "https://image.tmdb.org/t/p/w780/u8m7yZos0NNBHnJE00PixgYK2yz.jpg", "https://image.tmdb.org/t/p/w780/wMQgG7pzfFoorL4JC0U9YKlkcSl.jpg", "https://image.tmdb.org/t/p/w780/xHDynIimfsgj0ZOs0j5ma8v1vmM.jpg"],
    studio: "Fox Searchlight Pictures · Studio Babelsberg",
  },
  {
    id: "moonrise-kingdom",
    title: { ko: "문라이즈 킹덤", en: "Moonrise Kingdom", ja: "ムーンライズ・キングダム" },
    credit: { ko: "웨스 앤더슨 · 촬영 로버트 예먼 · 2012", en: "Wes Anderson · DP Robert Yeoman · 2012", ja: "ウェス・アンダーソン · 撮影 ロバート・イェーマン · 2012" },
    lesson: { ko: "정중앙 대칭 구도와 단정한 황록색 팔레트를 배워보세요. 동화책 같은 색면이 1960년대의 향수를 빚어냅니다.", en: "Learn dead-centre symmetry and a tidy yellow-green palette, where storybook colour blocks conjure 1960s nostalgia.", ja: "ど真ん中の対称構図と端正な黄緑のパレットを学べます。絵本のような色面が1960年代のノスタルジーを生み出します。" },
    curation: { ko: "앤더슨과 예먼은 화면을 한 권의 그림책처럼 다룹니다. 인물과 사물을 정중앙에 두는 대칭 구도, 직각으로만 움직이는 카메라가 세계에 또박또박한 질서를 부여하고, 바랜 노랑과 풀빛 초록의 팔레트는 1960년대의 따뜻한 향수를 입힙니다. 색과 소품, 자수와 글자체까지 통제된 미장센은 어린 두 사람의 순수한 동화를 정밀한 디오라마로 완성합니다. 색면 구성과 대칭이 어떻게 분명한 톤을 만드는지 배우기 좋은 작품입니다.", en: "Anderson and Yeoman treat the frame like a picture book. Dead-centre symmetry and a camera that moves only in right angles impose a crisp order on the world, while a palette of faded yellows and grassy greens layers on warm 1960s nostalgia. Mise-en-scene controlled down to the props, embroidery and typefaces turns a young couple's innocent fable into a precise diorama. It is an ideal study in how colour-block composition and symmetry build a clear, unmistakable tone.", ja: "アンダーソンとイェーマンは画面を一冊の絵本のように扱います。人物や物をど真ん中に置く対称構図、直角にしか動かないカメラが世界にきっちりした秩序を与え、褪せた黄色と草色の緑のパレットが温かな1960年代のノスタルジーをまとわせます。色や小道具、刺繍や書体まで統御されたミザンセーヌが、幼い二人の純真な童話を精密なジオラマへと仕上げます。色面構成と対称が明確なトーンをいかに作るかを学ぶのに最適な一本です。" },
    url: "https://www.themoviedb.org/movie/83666",
    image: "https://image.tmdb.org/t/p/w780/qWGLq6UeiUh8ei0LwSl4AmXN581.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/qWGLq6UeiUh8ei0LwSl4AmXN581.jpg", "https://image.tmdb.org/t/p/w780/oBc3pFCBhTR9DbI0FMrvMcVNF45.jpg", "https://image.tmdb.org/t/p/w780/tqoIZNaiKBRhyBZXu9G52jBMkwg.jpg", "https://image.tmdb.org/t/p/w780/bsYv9IFIGfpAV0oUbe7YTiyxhox.jpg"],
    studio: "Indian Paintbrush · American Empirical Pictures",
  },
  {
    id: "the-royal-tenenbaums",
    title: { ko: "로얄 테넌바움", en: "The Royal Tenenbaums", ja: "ザ・ロイヤル・テネンバウムズ" },
    credit: { ko: "웨스 앤더슨 · 촬영 로버트 예먼 · 2001", en: "Dir. Wes Anderson · DP Robert Yeoman · 2001", ja: "監督 ウェス・アンダーソン · 撮影 ロバート・イェーマン · 2001" },
    lesson: { ko: "정면을 향한 평면적 구도와 따뜻한 인형의 집 같은 색감으로, 슬픈 이야기를 어떻게 동화처럼 정돈하는지 배워 보세요. 균형 잡힌 프레임 속에 쓸쓸함이 깃듭니다.", en: "Learn how flat, head-on framing and a warm dollhouse palette tidy a sad story into something storybook-like. Melancholy lives inside the perfectly balanced frame.", ja: "正面を向いた平面的な構図と、温かなドールハウスのような色彩で、悲しい物語をいかに絵本のように整えるかを学べます。均整のとれたフレームに寂しさが宿ります。" },
    curation: { ko: "웨스 앤더슨과 촬영감독 로버트 예먼은 인물을 화면 한가운데 정면으로 세우고, 카메라를 벽과 평행하게 두어 마치 인형의 집을 들여다보는 듯한 평면 구도를 완성합니다. 바랜 황톳빛과 따뜻한 톤으로 통일된 미술은 어긋난 가족의 이야기를 아련한 동화처럼 감싸 안죠. 정중앙 배치와 좌우 대칭은 통제된 질서감을 주는 동시에, 그 안에 갇힌 인물들의 고독을 도드라지게 만듭니다. 구도와 색 디자인이 어떻게 감정의 톤을 결정하는지, 그 정밀한 설계를 공부하기에 좋은 작품입니다.", en: "Wes Anderson and cinematographer Robert Yeoman place their characters dead-centre and facing the lens, keeping the camera parallel to the walls so each shot feels like peering into a dollhouse. A unified palette of faded ochres and warm tones wraps this story of a fractured family in wistful, storybook softness. The centred, symmetrical arrangements lend a controlled sense of order while throwing the loneliness of the people trapped inside it into sharp relief. It's a fine study in how composition and colour design set the emotional key of a film.", ja: "ウェス・アンダーソンと撮影監督ロバート・イェーマンは、人物を画面の中央に正面で立たせ、カメラを壁と平行に保つことで、まるでドールハウスを覗き込むような平面的構図を完成させます。褪せた黄土色と温かなトーンで統一された美術が、すれ違う家族の物語を切ない絵本のように包み込みます。中央配置と左右対称は統制された秩序感を与えると同時に、その中に閉じ込められた人物たちの孤独を際立たせます。構図と色彩設計がいかに感情のトーンを決めるか、その緻密な設計を学ぶのに格好の作品です。" },
    url: "https://www.themoviedb.org/movie/9428",
    image: "https://image.tmdb.org/t/p/w780/cbuX448RKetr5Y5cZkmJEfu3xji.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/cbuX448RKetr5Y5cZkmJEfu3xji.jpg", "https://image.tmdb.org/t/p/w780/aoy8HmDvoGPwWiGnQKFErg7FVYB.jpg", "https://image.tmdb.org/t/p/w780/g2s22rGjCTCYsjI1iAflem7HjdG.jpg", "https://image.tmdb.org/t/p/w780/9NpvsVQxFKJZyhJYI81XsaF9NST.jpg"],
    studio: "Touchstone Pictures · American Empirical Pictures",
  },
  {
    id: "the-french-dispatch",
    title: { ko: "프렌치 디스패치", en: "The French Dispatch", ja: "フレンチ・ディスパッチ ザ・リバティ、カンザス・イヴニング・サン別冊" },
    credit: { ko: "웨스 앤더슨 · 촬영 로버트 예먼 · 2021", en: "Dir. Wes Anderson · DP Robert Yeoman · 2021", ja: "監督 ウェス・アンダーソン · 撮影 ロバート・イェーマン · 2021" },
    lesson: { ko: "흑백과 컬러를 오가고 화면비를 바꿔가며, 색과 프레임의 형식 자체를 이야기의 도구로 쓰는 법을 배웁니다.", en: "Learn to use colour and frame format as storytelling tools, switching between black-and-white and colour and shifting aspect ratios.", ja: "白黒とカラーを行き来しアスペクト比を変えながら、色と画面の形式そのものを語りの道具に使う術を学びます。" },
    curation: { ko: "앤더슨과 예먼은 한 잡지의 지면을 영화로 옮기듯, 기사마다 색감과 화면비를 바꿔 챕터를 구분합니다. 흑백으로 가라앉았다 돌연 한 컷만 컬러로 터지는 순간은 강조와 회상을 색으로 조판하는 편집 행위에 가깝습니다. 늘 그렇듯 정중앙 대칭과 평면적 정면 구도는 화면을 삽화처럼 단정하게 정렬합니다. 색과 비율을 내용에 맞춰 갈아 끼우는 형식 실험을 관찰하기에 더없이 풍성한 텍스트입니다.", en: "Anderson and Yeoman translate a magazine's pages into cinema, separating chapters by shifting palette and aspect ratio with each article. The moments when a scene settles into black-and-white and then a single shot bursts into colour are close to typesetting emphasis and memory with hue. As ever, dead-centre symmetry and flat frontal compositions arrange the frame as neatly as an illustration. It is a richly rewarding text for observing formal experiment that swaps colour and ratio to suit the content.", ja: "アンダーソンとイェーマンは雑誌の誌面を映画へ移すように、記事ごとに色調と画面比を変えてチャプターを区切ります。白黒に沈んだのち突然一カットだけがカラーに弾ける瞬間は、強調や回想を色で組版する編集行為に近いものです。いつものように中央対称と平面的な正面構図が、画面を挿絵のように端正に整えます。色と比率を内容に合わせて差し替える形式的実験を観察するのに、この上なく豊かなテキストです。" },
    url: "https://www.themoviedb.org/movie/542178",
    image: "https://image.tmdb.org/t/p/w780/jf31WjladY3xIHJ110RtPWZ84gf.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/jf31WjladY3xIHJ110RtPWZ84gf.jpg", "https://image.tmdb.org/t/p/w780/nc3EnMLAh0NVwVBkhk1776FUgud.jpg", "https://image.tmdb.org/t/p/w780/kR9HqBCUDevbTc93TMS1XmiRRem.jpg"],
    studio: "Indian Paintbrush · American Empirical Pictures",
  },
  {
    id: "blade-runner-2049",
    title: { ko: "블레이드 러너 2049", en: "Blade Runner 2049", ja: "ブレードランナー 2049" },
    credit: { ko: "드니 빌뇌브 · 촬영 로저 디킨스 · 2017", en: "Denis Villeneuve · DP Roger Deakins · 2017", ja: "ドゥニ・ヴィルヌーヴ · 撮影 ロジャー・ディーキンス · 2017" },
    lesson: { ko: "구역마다 색을 하나로 통일하는 색면 설계를 배워보세요. 주황색, 청록색처럼 장면 전체를 단색으로 칠하고 광대한 빈 공간을 두는 연출이 고독을 어떻게 시각화하는지 보여줍니다.", en: "Study how each zone is painted a single colour. Drenching scenes in orange or teal and surrounding figures with vast emptiness makes solitude visible.", ja: "区域ごとに色を一つに統一する色面設計を学べます。オレンジや青緑で場面全体を染め、広大な空白を置く演出が孤独をどう可視化するかがわかります。" },
    curation: { ko: "로저 디킨스는 미래 도시를 거대한 색면으로 나눕니다. 사막을 뒤덮은 주황빛, 차갑게 가라앉은 청록빛처럼 구역마다 하나의 색이 지배하고, 그 사이를 작게 가로지르는 인물은 압도적인 스케일 속에서 더없이 외로워 보이죠. 빛과 안개, 거대한 네거티브 스페이스를 결합해 디스토피아의 적막을 시각으로 번역해냅니다. 색과 규모, 여백만으로 감정을 설계하는 법을 익히고 싶다면 반드시 들여다봐야 할 작품입니다.", en: "Roger Deakins carves the future city into vast blocks of colour. A single hue rules each zone, orange smothering the desert, teal cooling the interiors, and the lone figure crossing it looks unbearably small against the scale. Light, haze and enormous negative space combine to translate dystopian silence into pure image. If you want to design emotion with colour, scale and emptiness, this is essential viewing.", ja: "ロジャー・ディーキンスは未来都市を巨大な色面に分割します。砂漠を覆うオレンジ、冷たく沈む青緑のように、区域ごとに一つの色が支配し、その間を小さく横切る人物は圧倒的なスケールの中でこの上なく孤独に見えます。光と霧、巨大な余白を組み合わせ、ディストピアの静寂を映像へと翻訳します。色と規模、余白だけで感情を設計する術を学びたいなら、必ず見るべき一作です。" },
    url: "https://www.themoviedb.org/movie/335984",
    image: "https://image.tmdb.org/t/p/w780/ilRyazdMJwN05exqhwK4tMKBYZs.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/ilRyazdMJwN05exqhwK4tMKBYZs.jpg", "https://image.tmdb.org/t/p/w780/9AU3kxNMM6AGofeC1uOtm4etsNj.jpg", "https://image.tmdb.org/t/p/w780/askFH4GSk2u9z3ZE5ypdKIMeqLJ.jpg", "https://image.tmdb.org/t/p/w780/m7ynwXIvSnhxQPR6pOICrC0L2sO.jpg"],
    studio: "Alcon Entertainment · Columbia Pictures",
  },
  {
    id: "dune",
    title: { ko: "듄", en: "Dune", ja: "デューン 砂の惑星" },
    credit: { ko: "드니 빌뇌브 · 촬영 그레이그 프레이저 · 2021", en: "Denis Villeneuve · DP Greig Fraser · 2021", ja: "ドゥニ・ヴィルヌーヴ · 撮影 グレイグ・フレイザー · 2021" },
    lesson: { ko: "거대한 스케일과 단색의 사막을 배워보세요. 단단한 자연광이 인물을 압도적인 풍경 속 한 점으로 만듭니다.", en: "Learn monumental scale and a monochrome desert, where hard natural light reduces figures to a single point in vast terrain.", ja: "巨大なスケールと単色の砂漠を学べます。硬い自然光が人物を圧倒的な風景の中の一点へと変えます。" },
    curation: { ko: "빌뇌브와 프레이저는 절제된 단색 팔레트로 행성의 거대함을 빚어냅니다. 모래의 황토색과 금속의 회색으로 색을 덜어내고, 그림자가 또렷한 단단한 자연광을 써서 사막을 가혹하고 신성한 공간으로 만듭니다. 인물은 늘 풍경에 비해 작게 배치되어 자연 앞 인간의 미미함과 운명의 무게를 동시에 드러냅니다. 스케일과 빛의 질감이 어떻게 서사의 규모를 시각화하는지 보여주는 교본입니다.", en: "Villeneuve and Fraser shape a planet's vastness through a restrained, monochrome palette. Colour is pared back to ochre sand and metallic grey, and hard natural light with sharp shadows renders the desert as a harsh, sacred space. Figures are always placed small against the landscape, revealing both human insignificance before nature and the weight of destiny. It is a model of how scale and the texture of light can visualise the sheer magnitude of a story.", ja: "ヴィルヌーヴとフレイザーは抑制された単色のパレットで惑星の巨大さを造形します。色を砂の黄土色と金属の灰色へとそぎ落とし、影のくっきりした硬い自然光で砂漠を過酷で神聖な空間に変えます。人物は常に風景に対して小さく配置され、自然の前の人間のちっぽけさと運命の重みを同時に映し出します。スケールと光の質感がいかに物語の規模を可視化するかを示す教本です。" },
    url: "https://www.themoviedb.org/movie/438631",
    image: "https://image.tmdb.org/t/p/w780/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg", "https://image.tmdb.org/t/p/w780/h3HsfV8Kn9Sz2QWUYYdP5ya23hx.jpg", "https://image.tmdb.org/t/p/w780/zRKQW58MBEY078AxkHxEJzUskCl.jpg", "https://image.tmdb.org/t/p/w780/qVgZu5BTx6pu4owCvVOm4zjTfOi.jpg"],
    studio: "Legendary Pictures",
  },
  {
    id: "sicario",
    title: { ko: "시카리오: 암살자의 도시", en: "Sicario", ja: "ボーダーライン" },
    credit: { ko: "드니 빌뇌브 · 촬영 로저 디킨스 · 2015", en: "Dir. Denis Villeneuve · DP Roger Deakins · 2015", ja: "監督 ドゥニ・ヴィルヌーヴ · 撮影 ロジャー・ディーキンス · 2015" },
    lesson: { ko: "광활한 풍경과 황혼을 등진 실루엣으로 어떻게 불길함을 빚어내는지 배워 보세요. 위협은 인물이 아니라 텅 빈 지평선에서 옵니다.", en: "Learn how vast landscapes and silhouettes against dusk shape pure menace. The threat comes not from the characters but from the empty horizon.", ja: "広大な風景と夕暮れを背にしたシルエットで、いかに不吉さを形づくるかを学べます。脅威は人物ではなく、空虚な地平線から訪れます。" },
    curation: { ko: "드니 빌뇌브와 촬영감독 로저 디킨스는 미국과 멕시코 국경의 메마른 풍경을 위에서 내려다보거나 멀리 밀어내며, 인물을 작게 만들고 땅 자체를 위협의 주체로 세웁니다. 해 질 녘, 능선 위에 검은 실루엣으로 늘어선 요원들의 행렬은 빛이 사라지는 자리에 불안을 채워 넣죠. 야간투시경의 녹색 화면 같은 시각적 전환은 우리가 안전한 시야를 잃었음을 몸으로 느끼게 합니다. 풍경과 빛을 정서의 도구로 다루는 법을 배우기에 디킨스만 한 스승이 없습니다.", en: "Denis Villeneuve and cinematographer Roger Deakins shoot the parched US–Mexico border from high above or far back, shrinking the characters and making the land itself the source of threat. At dusk, the line of agents reduced to black silhouettes along a ridge fills the fading light with dread. Visual shifts like the green wash of night-vision make us feel, in the body, that we have lost safe sight. For learning to wield landscape and light as instruments of feeling, there is no better teacher than Deakins.", ja: "ドゥニ・ヴィルヌーヴと撮影監督ロジャー・ディーキンスは、乾いたアメリカ・メキシコ国境の風景を高みから見下ろし、あるいは遠くへ引いて、人物を小さくし、大地そのものを脅威の主体に据えます。日暮れ時、稜線の上に黒いシルエットとして連なる捜査官たちの列が、光の消える場所に不安を満たしていきます。暗視ゴーグルの緑の画面のような視覚的転換は、私たちが安全な視界を失ったことを身体で感じさせます。風景と光を感情の道具として扱う術を学ぶなら、ディーキンスほどの師はいません。" },
    url: "https://www.themoviedb.org/movie/273481",
    image: "https://image.tmdb.org/t/p/w780/meeileDF37uB8ykIs4iFb713ABO.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/meeileDF37uB8ykIs4iFb713ABO.jpg", "https://image.tmdb.org/t/p/w780/uo2uaD6vNi62gyf13UMQ3cp7z4O.jpg", "https://image.tmdb.org/t/p/w780/aBqc9cO8J9MXzZhiwTSmwjxK6MU.jpg"],
    studio: "Lionsgate · Black Label Media",
  },
  {
    id: "days-of-heaven",
    title: { ko: "천국의 나날들", en: "Days of Heaven", ja: "天国の日々" },
    credit: { ko: "테런스 맬릭 · 촬영 네스토르 알멘드로스 · 1978", en: "Dir. Terrence Malick · DP Néstor Almendros · 1978", ja: "監督 テレンス・マリック · 撮影 ネストール・アルメンドロス · 1978" },
    lesson: { ko: "해 질 녘 황금빛 자연광과 하늘을 등진 들판 구도에서, 시간을 골라 빛을 얻는 인내를 배웁니다.", en: "Learn the patience of choosing a time of day to find light from golden magic-hour sun and fields set against the sky.", ja: "黄昏の金色の自然光と空を背にした畑の構図から、時間を選んで光を得る忍耐を学びます。" },
    curation: { ko: "알멘드로스는 해가 지기 직전 단 몇십 분의 매직아워에만 촬영을 몰아, 들판 전체를 호박빛으로 물들였습니다. 인공조명을 거의 쓰지 않고 낮게 깔린 빛과 역광에 기대니, 밀밭과 인물이 하늘을 배경으로 실루엣처럼 떠오릅니다. 지평선을 낮게 두는 구도는 거대한 하늘과 작은 사람의 대비를 만들어 서사에 비극적 숭고함을 입힙니다. 빛이 가장 아름다운 순간을 기다렸다 단번에 담아내는 자연광 촬영의 원형을 보여 줍니다.", en: "Almendros concentrated shooting into the few dozen minutes of magic hour just before sunset, soaking entire fields in amber. Using almost no artificial light and leaning on low, raking light and backlight, the wheat and the figures rise like silhouettes against the sky. Keeping the horizon low builds a contrast between the vast sky and the small human, lending the story a tragic sublimity. It shows the very prototype of natural-light cinematography that waits for light's most beautiful moment and captures it in a single pass.", ja: "アルメンドロスは日没直前のわずか数十分のマジックアワーだけに撮影を集中させ、畑全体を琥珀色に染めました。人工照明をほとんど使わず低く差す光と逆光に頼ることで、麦畑も人物も空を背にシルエットのように浮かび上がります。地平線を低く置く構図は、広大な空と小さな人間の対比を生み、物語に悲劇的な崇高さをまといます。光が最も美しい瞬間を待って一気に収める、自然光撮影の原型を見せてくれます。" },
    url: "https://www.themoviedb.org/movie/16642",
    image: "https://image.tmdb.org/t/p/w780/5JrPWR6ve6gry6LG8SKr6tsQSBo.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/5JrPWR6ve6gry6LG8SKr6tsQSBo.jpg", "https://image.tmdb.org/t/p/w780/zUqIL6H6d44se9ZOsfvvCuOsbap.jpg", "https://image.tmdb.org/t/p/w780/gOhWK61GUwGCpgt0L1T8gVz6XVW.jpg", "https://image.tmdb.org/t/p/w780/1JUz4tFPtIcC6mqAEjTsHMZRBJ.jpg"],
    studio: "Paramount Pictures",
  },
  {
    id: "the-tree-of-life",
    title: { ko: "트리 오브 라이프", en: "The Tree of Life", ja: "ツリー・オブ・ライフ" },
    credit: { ko: "테런스 맬릭 · 촬영 에마뉘엘 루베즈키 · 2011", en: "Terrence Malick · DP Emmanuel Lubezki · 2011", ja: "テレンス・マリック · 撮影 エマニュエル・ルベツキ · 2011" },
    lesson: { ko: "자연광만으로 촬영하는 유려한 핸드헬드 카메라를 배워보세요. 광각 렌즈가 끊임없이 움직이며 빛을 따라가는 방식이 기억과 감정을 어떻게 담아내는지 보여줍니다.", en: "Learn the roaming handheld camera shot in natural light alone. A wide lens drifting after the sun captures memory and feeling rather than plot.", ja: "自然光だけで撮る流麗な手持ちカメラを学べます。広角レンズが絶え間なく動き光を追う手法が、記憶と感情をどう捉えるかがわかります。" },
    curation: { ko: "에마뉘엘 루베즈키는 인공조명을 거의 쓰지 않고 오직 자연광만으로 화면을 채웁니다. 광각 렌즈를 든 카메라는 정해진 구도에 멈추는 대신 빛과 인물 사이를 끊임없이 떠돌며, 잔디와 우주를 같은 경외감으로 바라보죠. 매직아워의 부드러운 빛과 유영하는 움직임이 결합해 영화는 한 사람의 기억을 더듬는 듯한 질감을 얻습니다. 빛을 좇는 카메라가 어떻게 시간과 감정을 담을 수 있는지, 자연광 촬영의 정점을 보여주는 작품입니다.", en: "Emmanuel Lubezki lights almost nothing artificially, filling the frame with daylight alone. The wide-lens camera never settles into a fixed composition; it roams between light and figure, regarding a blade of grass and the cosmos with the same awe. Soft magic-hour light and that drifting motion give the film the texture of someone sifting through memory. As a peak of natural-light cinematography, it shows how a camera chasing the sun can hold time and feeling.", ja: "エマニュエル・ルベツキは人工照明をほとんど使わず、自然光だけで画面を満たします。広角レンズのカメラは定まった構図に止まらず、光と人物の間を絶えず漂い、草の葉と宇宙を同じ畏敬の念で見つめます。マジックアワーの柔らかな光と遊泳するような動きが結びつき、映画は一人の記憶をたどるような質感を得ます。光を追うカメラが時間と感情をいかに捉えうるか、自然光撮影の頂点を示す一作です。" },
    url: "https://www.themoviedb.org/movie/8967",
    image: "https://image.tmdb.org/t/p/w780/krDjqWqLAewVYiU8fDQLHO7gPmf.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/krDjqWqLAewVYiU8fDQLHO7gPmf.jpg", "https://image.tmdb.org/t/p/w780/nMez2WaB7gHe3vJYfqT5mmYY57t.jpg", "https://image.tmdb.org/t/p/w780/xq1HIwZq9VbuvMQELAua1nqEkH.jpg"],
    studio: "River Road Entertainment",
  },
  {
    id: "oldboy",
    title: { ko: "올드보이", en: "Oldboy", ja: "オールド・ボーイ" },
    credit: { ko: "박찬욱 · 촬영 정정훈 · 2003", en: "Park Chan-wook · DP Jeong Jeong-hun · 2003", ja: "パク・チャヌク · 撮影 チョン・ジョンフン · 2003" },
    lesson: { ko: "측면으로 흐르는 복도 격투를 한 호흡에 담은 롱테이크를 배워보세요. 녹색과 호박색의 팔레트가 폭력에 기묘한 무게를 더합니다.", en: "Learn the side-scrolling corridor fight captured in one breath, where a green-amber palette lends the violence an eerie weight.", ja: "横へ流れる廊下の格闘を一息で収めたロングテイクを学べます。緑と琥珀のパレットが暴力に奇妙な重みを加えます。" },
    curation: { ko: "박찬욱과 정정훈은 복도 격투 시퀀스를 측면으로 따라가는 단 한 번의 롱테이크로 찍어, 게임의 횡스크롤처럼 평면적이면서도 처절한 리듬을 만들어냅니다. 카메라는 물러서지 않고 인물과 같은 높이에서 끈질기게 움직이며 관객을 지친 싸움 한가운데 세워 둡니다. 탁한 녹색과 호박색이 깔린 화면은 복수의 끈적임과 피로를 색으로 번역합니다. 한 컷의 운동과 색이 어떻게 감정의 질량을 만드는지 보여주는 대표적인 장면입니다.", en: "Park Chan-wook and Jeong Jeong-hun shoot the corridor fight as a single lateral long take, flat like a side-scrolling game yet brutally rhythmic. The camera never retreats, tracking at the characters' own height with dogged persistence and stranding us in the middle of an exhausting brawl. A frame washed in murky green and amber translates the stickiness and fatigue of vengeance into colour. It is a landmark example of how the motion and palette of a single shot can give emotion real mass.", ja: "パク・チャヌクとチョン・ジョンフンは廊下の格闘シーンを横へ追う一度きりのロングテイクで撮り、横スクロールゲームのように平面的でありながら凄絶なリズムを生み出します。カメラは退かず、人物と同じ高さで執拗に動き、観客を疲弊した戦いの只中に立たせます。濁った緑と琥珀色に沈んだ画面は、復讐の粘りと疲労を色へと翻訳します。一つのショットの運動と色がいかに感情の質量を作るかを示す代表的な場面です。" },
    url: "https://www.themoviedb.org/movie/670",
    image: "https://image.tmdb.org/t/p/w780/hKNGaQFzg4RxyMWIGGnYGW5b2Xh.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/hKNGaQFzg4RxyMWIGGnYGW5b2Xh.jpg", "https://image.tmdb.org/t/p/w780/tcbzsdWpdidbN7zbOymlRKfIHVg.jpg", "https://image.tmdb.org/t/p/w780/sdwjQEM869JFwMytTmvr6ggvaUl.jpg", "https://image.tmdb.org/t/p/w780/47rioCQJLDe6gT7NYdPf7IRy3Nu.jpg"],
    studio: "Show East · Egg Film",
  },
  {
    id: "the-handmaiden",
    title: { ko: "아가씨", en: "The Handmaiden", ja: "お嬢さん" },
    credit: { ko: "박찬욱 · 촬영 정정훈 · 2016", en: "Dir. Park Chan-wook · DP Chung Chung-hoon · 2016", ja: "監督 パク・チャヌク · 撮影 チョン・ジョンフン · 2016" },
    lesson: { ko: "공들인 대칭 구도와 거울을 활용해, 욕망과 시선을 어떻게 시각적으로 설계하는지 배워 보세요. 화면의 정교함 자체가 긴장을 만듭니다.", en: "Learn how lush symmetry and mirrors visually design desire and the gaze. The very precision of the frame becomes tension.", ja: "凝った対称構図と鏡を用いて、欲望と視線をいかに視覚的に設計するかを学べます。画面の精緻さそのものが緊張を生みます。" },
    curation: { ko: "박찬욱과 촬영감독 정정훈은 일제강점기를 배경으로 한 저택을 좌우 대칭의 정교한 구도로 빚어, 인물들의 욕망과 음모를 호화로운 표면 아래 숨겨 둡니다. 거울과 창, 미닫이문이 만드는 겹겹의 프레임은 누가 누구를 보고 또 속이는지를 시각적으로 배치하며, 보는 행위 자체를 영화의 주제로 끌어올리죠. 같은 사건을 다른 시점으로 되짚는 구성은 카메라의 위치가 곧 진실의 위치임을 일깨웁니다. 정밀한 미장센으로 시선과 욕망을 다루는 법을 배우기에 탁월한 작품입니다.", en: "Park Chan-wook and cinematographer Chung Chung-hoon render a colonial-era estate in exquisitely symmetrical compositions, hiding the characters' desires and schemes beneath a lavish surface. Layered frames made of mirrors, windows and sliding doors map out who watches and deceives whom, lifting the act of looking into the film's very subject. By revisiting the same events from shifting viewpoints, the structure reminds us that the camera's position is the position of truth. It's a superb study in handling gaze and desire through precise mise-en-scène.", ja: "パク・チャヌクと撮影監督チョン・ジョンフンは、日本統治期を舞台にした邸宅を左右対称の精緻な構図で描き上げ、人物たちの欲望と陰謀を豪奢な表面の下に隠します。鏡や窓、引き戸がつくる幾重ものフレームが、誰が誰を見て、また欺くのかを視覚的に配置し、見るという行為そのものを映画の主題へと引き上げます。同じ事件を異なる視点で辿り直す構成は、カメラの位置こそが真実の位置であることを気づかせます。精密なミザンセーヌで視線と欲望を扱う術を学ぶのに、卓越した作品です。" },
    url: "https://www.themoviedb.org/movie/290098",
    image: "https://image.tmdb.org/t/p/w780/9o9ci7ZH9chSy8B7YXCBYih8Kkd.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/9o9ci7ZH9chSy8B7YXCBYih8Kkd.jpg", "https://image.tmdb.org/t/p/w780/3upEZ0ltY7WwOSFVXrtiP34D48p.jpg", "https://image.tmdb.org/t/p/w780/eUKJrORgXWAMFoBwTqJgwqSFprs.jpg", "https://image.tmdb.org/t/p/w780/nOK0uEDnp99ZYl2ihCZwviNaSv2.jpg"],
    studio: "Moho Film · Yong Film",
  },
  {
    id: "parasite",
    title: { ko: "기생충", en: "Parasite", ja: "パラサイト 半地下の家族" },
    credit: { ko: "봉준호 · 촬영 홍경표 · 2019", en: "Dir. Bong Joon-ho · DP Hong Kyung-pyo · 2019", ja: "監督 ポン・ジュノ · 撮影 ホン・ギョンピョ · 2019" },
    lesson: { ko: "계급을 수직으로 배치하고 계단과 모더니즘 저택을 활용해, 공간의 높낮이로 권력 관계를 보여 주는 법을 배웁니다.", en: "Learn to show power relations through vertical space, staging class up and down stairs and across a modernist house.", ja: "階級を垂直に配置し階段とモダニズム邸宅を使い、空間の高低で権力関係を見せる術を学びます。" },
    curation: { ko: "봉준호와 홍경표는 반지하와 언덕 위 저택이라는 수직 좌표 위에 인물들을 배치해, 계급을 곧 높낮이로 번역합니다. 모더니즘 주택의 긴 가로선과 큰 통창은 부유함의 여백을 만들고, 끝없이 오르내리는 계단은 신분 이동의 통로이자 함정이 됩니다. 빛은 위층에 풍성하고 아래로 갈수록 사위어 들며, 같은 비라도 누구에게는 정원이고 누구에게는 침수가 됩니다. 공간 설계와 프레임의 높이만으로 사회를 그리는 연출을 공부하기에 탁월한 작품입니다.", en: "Bong Joon-ho and Hong Kyung-pyo place their characters along a vertical axis of semi-basement and hilltop mansion, translating class directly into high and low. The modernist house's long horizontals and wide windows create the breathing room of wealth, while the stairs climbed and descended endlessly become both a passage and a trap of social standing. Light is abundant on the upper floors and fades the further down you go, so that the same rain is a garden to one family and a flood to another. It is an outstanding film for studying direction that draws a whole society through spatial design and the height of the frame alone.", ja: "ポン・ジュノとホン・ギョンピョは、半地下と丘の上の邸宅という垂直の座標上に人物を配置し、階級をそのまま高低へと翻訳します。モダニズム住宅の長い水平線と大きな窓は富の余白をつくり、絶え間なく上り下りする階段は身分移動の通路であり罠ともなります。光は上階に豊かで、下へ行くほど痩せ細り、同じ雨でも誰かには庭で誰かには浸水となります。空間設計とフレームの高さだけで社会を描く演出を学ぶのに、卓越した一本です。" },
    url: "https://www.themoviedb.org/movie/496243",
    image: "https://image.tmdb.org/t/p/w780/25tz24hlrqAbjhpHx1FhmfPH8Qf.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/25tz24hlrqAbjhpHx1FhmfPH8Qf.jpg", "https://image.tmdb.org/t/p/w780/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", "https://image.tmdb.org/t/p/w780/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg", "https://image.tmdb.org/t/p/w780/cM0pnzCF6T7u1AAEYgyCG6Sua6k.jpg"],
    studio: "Barunson E&A",
  },
  {
    id: "decision-to-leave",
    title: { ko: "헤어질 결심", en: "Decision to Leave", ja: "別れる決心" },
    credit: { ko: "박찬욱 · 촬영 김지용 · 2022", en: "Park Chan-wook · DP Kim Ji-yong · 2022", ja: "パク・チャヌク · 撮影 キム・ジヨン · 2022" },
    lesson: { ko: "안개 낀 푸른빛 톤과 매치 컷을 배워보세요. 시선이 다른 장소와 시간으로 매끄럽게 이어지는 편집이 보는 것과 그리워하는 마음을 어떻게 화면으로 옮기는지 보여줍니다.", en: "Study the misty blue palette and match cuts. Edits that glide one gaze into another time and place turn watching and longing into image.", ja: "霧がかった青のトーンとマッチカットを学べます。視線を別の場所と時間へ滑らかにつなぐ編集が、見ることと恋しさをどう映像に移すかがわかります。" },
    curation: { ko: "박찬욱과 김지용은 안개에 잠긴 푸른빛과 초록빛으로 영화 전체를 적십니다. 형사의 시선과 용의자의 자리를 매끄럽게 잇는 매치 컷은 공간과 시간을 접어 두 사람의 거리를 시각적으로 좁혔다 벌리죠. 관찰하는 자와 관찰당하는 자, 보는 것과 그리워하는 것이 화면 안에서 끝없이 자리를 바꿉니다. 시선과 편집이 어떻게 감정의 문법이 되는지, 한 컷의 연결까지 설계된 정교함을 배우기 좋은 작품입니다.", en: "Park Chan-wook and Kim Ji-yong steep the whole film in misty blues and greens. Match cuts slide the detective's gaze straight into the suspect's place, folding space and time to pull the two closer and push them apart. Watcher and watched, seeing and longing, keep trading positions inside the frame. As a study in how gaze and editing become a grammar of feeling, its precision down to a single cut is worth learning from.", ja: "パク・チャヌクとキム・ジヨンは、霧に沈む青と緑で映画全体を染めます。刑事の視線と容疑者の場所を滑らかにつなぐマッチカットは、空間と時間を畳み、二人の距離を視覚的に縮めては広げます。見る者と見られる者、見ることと恋しさが、画面の中で絶えず位置を入れ替えます。視線と編集がいかに感情の文法になるか、一カットのつなぎまで設計された精緻さを学ぶのに最適な一作です。" },
    url: "https://www.themoviedb.org/movie/705996",
    image: "https://image.tmdb.org/t/p/w780/A1bWhTFQKkhF1yhSKWosSyzn2Hp.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/A1bWhTFQKkhF1yhSKWosSyzn2Hp.jpg", "https://image.tmdb.org/t/p/w780/naJGUVlXMr5JzADLqel1WL7iqmV.jpg", "https://image.tmdb.org/t/p/w780/y7efrL5RlIRsGfrhcaiP35V1x2g.jpg", "https://image.tmdb.org/t/p/w780/9K39idcJKYZNKCwMbsQCmOCJPzY.jpg"],
    studio: "Moho Film · CJ ENM",
  },
  {
    id: "burning",
    title: { ko: "버닝", en: "Burning", ja: "バーニング 劇場版" },
    credit: { ko: "이창동 · 촬영 홍경표 · 2018", en: "Lee Chang-dong · DP Hong Kyung-pyo · 2018", ja: "イ・チャンドン · 撮影 ホン・ギョンピョ · 2018" },
    lesson: { ko: "해질녘 매직아워의 모호한 빛을 배워보세요. 사라져 가는 금빛 노을 속에서 평온과 불안이 한데 뒤섞입니다.", en: "Learn the ambiguous light of magic hour, where in a fading golden dusk calm and unease blur into one.", ja: "夕暮れのマジックアワーの曖昧な光を学べます。消えゆく金色の夕焼けの中で、平穏と不安が一つに溶け合います。" },
    curation: { ko: "이창동과 홍경표는 해가 막 지는 매직아워의 짧고 불안정한 빛을 붙잡아, 아름다움과 불길함이 분간되지 않는 정조를 만들어냅니다. 노을 속 춤 장면처럼, 황금빛은 따뜻하면서도 곧 어둠에 삼켜질 듯 위태롭게 흔들립니다. 색을 거의 비우고 자연광의 미묘한 변화에 모든 것을 맡긴 화면은 인물의 공허와 분노를 말없이 품습니다. 빛 하나로 분위기와 서스펜스를 동시에 빚는 법을 가르쳐 주는 작품입니다.", en: "Lee Chang-dong and Hong Kyung-pyo capture the brief, unstable light of magic hour just after sunset, conjuring a mood where beauty and menace can no longer be told apart. As in the dusk dance, the golden glow is warm yet trembles on the edge of being swallowed by dark. A frame nearly drained of colour, surrendered to the subtle shifts of natural light, silently holds the characters' emptiness and rage. It teaches how a single quality of light can build atmosphere and suspense at once.", ja: "イ・チャンドンとホン・ギョンピョは、日没直後のマジックアワーの短く不安定な光をとらえ、美しさと不吉さが区別できなくなる情緒を生み出します。夕焼けの中の踊りの場面のように、金色の光は温かくも、すぐ闇に呑まれそうに危うく揺れます。色をほとんど抜き、自然光の微妙な移ろいにすべてを委ねた画面が、人物の空虚と怒りを無言で抱きます。たった一つの光で雰囲気とサスペンスを同時に生む術を教えてくれる一本です。" },
    url: "https://www.themoviedb.org/movie/491584",
    image: "https://image.tmdb.org/t/p/w780/qQEt2FqF8McryFBNX30dyDJKiEK.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/qQEt2FqF8McryFBNX30dyDJKiEK.jpg", "https://image.tmdb.org/t/p/w780/rENYZSx6HFME7YLbbY0qGYayL7F.jpg", "https://image.tmdb.org/t/p/w780/3gSvNuM4ieYloFvZu0Zu0wyMNIU.jpg", "https://image.tmdb.org/t/p/w780/v6eOq707lwWFIG96Rv9sSR6lnnT.jpg"],
    studio: "Pinehouse Film · NOWFILM",
  },
  {
    id: "memories-of-murder",
    title: { ko: "살인의 추억", en: "Memories of Murder", ja: "殺人の追憶" },
    credit: { ko: "봉준호 · 촬영 김형구 · 2003", en: "Dir. Bong Joon-ho · DP Kim Hyung-koo · 2003", ja: "監督 ポン・ジュノ · 撮影 キム・ヒョング · 2003" },
    lesson: { ko: "탁 트인 농촌 들판과 낮은 시점의 첫 도랑 장면처럼, 풍경을 통해 어떻게 막막함과 미해결의 정서를 담는지 배워 보세요. 넓은 화면이 오히려 답답함을 부릅니다.", en: "Learn how open rural fields and the low-angle opening ditch shot carry a sense of helplessness and the unsolved. A wide frame can deepen suffocation rather than relieve it.", ja: "見晴らしの良い農村の田んぼや、低い視点の冒頭の溝のショットのように、風景を通していかに無力感と未解決の情緒を込めるかを学べます。広い画面がかえって息苦しさを呼びます。" },
    curation: { ko: "봉준호와 촬영감독 김형구는 1980년대 한국 농촌의 황금빛 논과 흙길을 넓은 화면에 펼쳐 놓고, 그 평온해 보이는 풍경 안에 풀리지 않는 사건의 막막함을 심어 둡니다. 영화를 여는 도랑 속 시신 장면은 낮은 시점과 들판의 넓이를 함께 써, 사건이 광활한 무관심 속에 묻혀 버릴 것을 예감하게 하죠. 흐린 하늘과 비, 진창의 질감은 진실에 다가갈수록 더 흐려지는 수사의 무력함을 화면으로 옮깁니다. 풍경과 빛으로 정서와 주제를 동시에 빚는 법을 배우기에 더없이 좋은 작품입니다.", en: "Bong Joon-ho and cinematographer Kim Hyung-koo spread the golden rice paddies and dirt roads of 1980s rural Korea across a wide frame, planting the helplessness of an unsolved case inside that deceptively peaceful landscape. The opening shot of a body in a ditch pairs a low angle with the breadth of the fields, foreboding that the crime will be swallowed by a vast indifference. Overcast skies, rain and the texture of mud translate into the image an investigation that grows murkier the closer it gets to the truth. It's an ideal study in shaping mood and theme at once through landscape and light.", ja: "ポン・ジュノと撮影監督キム・ヒョングは、1980年代韓国の農村の黄金色の田んぼと土の道を広い画面に広げ、その穏やかに見える風景の中に解けない事件の無力感を埋め込みます。映画を開く溝の中の遺体のショットは、低い視点と田畑の広さをともに用い、事件が広大な無関心の中に葬られることを予感させます。曇った空や雨、ぬかるみの質感が、真実に近づくほど濁っていく捜査の無力さを画面へと移します。風景と光で情緒と主題を同時に形づくる術を学ぶのに、この上ない作品です。" },
    url: "https://www.themoviedb.org/movie/11423",
    image: "https://image.tmdb.org/t/p/w780/6Kn6qW3an3DkPl3MahWemTzrjCt.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/6Kn6qW3an3DkPl3MahWemTzrjCt.jpg", "https://image.tmdb.org/t/p/w780/bBOgInuYcKB5rorSvRJ9PmSMxAn.jpg", "https://image.tmdb.org/t/p/w780/93jHHGMF3EOE5uiCri6roHkDOCZ.jpg", "https://image.tmdb.org/t/p/w780/2NArMoObkAbnIPvqlHC3gRGsfBb.jpg"],
    studio: "CJ Entertainment · Muhan Investment",
  },
  {
    id: "amelie",
    title: { ko: "아멜리에", en: "Amélie", ja: "アメリ" },
    credit: { ko: "장피에르 죄네 · 촬영 브뤼노 델보넬 · 2001", en: "Dir. Jean-Pierre Jeunet · DP Bruno Delbonnel · 2001", ja: "監督 ジャン＝ピエール・ジュネ · 撮影 ブリュノ・デルボネル · 2001" },
    lesson: { ko: "초록·빨강·금빛을 과장되게 끌어올린 색 보정에서, 채도와 색조로 동화 같은 분위기를 빚는 법을 배웁니다.", en: "Learn to craft a fairy-tale mood through saturation and tone from the exaggerated green, red and gold colour grade.", ja: "緑・赤・金を誇張して引き上げた色補正から、彩度と色調でおとぎ話のような空気を生む術を学びます。" },
    curation: { ko: "델보넬은 파리를 실제보다 따뜻하고 짙게 보정해, 도시 전체를 동화책의 삽화처럼 물들입니다. 초록과 빨강, 황금빛을 의도적으로 과포화시켜 골목과 카페가 비현실적으로 아늑하게 빛나도록 만들었습니다. 광각 렌즈의 부드러운 왜곡과 둥근 비네팅은 화면 가장자리를 감싸 안아, 관객을 주인공의 다정한 시선 안으로 끌어들입니다. 색만으로 현실에 마법을 덧입히는 컬러 디자인의 좋은 예입니다.", en: "Delbonnel pushes Paris warmer and richer than reality, washing the whole city in the tones of a storybook illustration. Greens, reds and golds are deliberately oversaturated so that alleys and cafés glow with an unreal cosiness. The soft distortion of wide lenses and a rounded vignette embrace the edges of the frame, drawing the viewer inside the heroine's tender gaze. It is a fine example of colour design that lays magic over the ordinary through hue alone.", ja: "デルボネルはパリを実際より暖かく濃く補正し、街全体を絵本の挿絵のような色に染めます。緑と赤と金をあえて過飽和にし、路地もカフェも非現実的なほど心地よく輝かせました。広角レンズの柔らかな歪みと丸いビネットが画面の縁を包み込み、観客を主人公の優しい眼差しの内側へと誘います。色だけで現実に魔法をまとわせるカラーデザインの好例です。" },
    url: "https://www.themoviedb.org/movie/194",
    image: "https://image.tmdb.org/t/p/w780/sylBlnpwqI9LAcyw7jH3oqazbAx.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/sylBlnpwqI9LAcyw7jH3oqazbAx.jpg", "https://image.tmdb.org/t/p/w780/9Y9K6LeLrMeofOvX7hZW36Aj3OG.jpg", "https://image.tmdb.org/t/p/w780/2WyjkKudTkDgtZo9CIN8NoPGHRB.jpg"],
    studio: "Victoires Productions · Tapioca Films",
  },
  {
    id: "moonlight",
    title: { ko: "문라이트", en: "Moonlight", ja: "ムーンライト" },
    credit: { ko: "배리 젱킨스 · 촬영 제임스 랙스턴 · 2016", en: "Barry Jenkins · DP James Laxton · 2016", ja: "バリー・ジェンキンス · 撮影 ジェームズ・ラクストン · 2016" },
    lesson: { ko: "검은 피부 위에 머무는 푸른빛과 보랏빛 조명을 배워보세요. 인물의 피부톤을 가장 아름답게 살리는 색온도 설계가 정체성과 감정을 어떻게 비추는지 보여줍니다.", en: "Learn how blue and purple light sit on Black skin. A colour-temperature design tuned to the subject's skin tone illuminates identity and emotion.", ja: "黒い肌の上に宿る青と紫の照明を学べます。人物の肌の色を最も美しく生かす色温度設計が、アイデンティティと感情をどう照らすかがわかります。" },
    curation: { ko: "제임스 랙스턴은 검은 피부를 어떻게 빛으로 조각할지 깊이 고민한 촬영을 보여줍니다. 푸른빛과 보랏빛이 감도는 조명은 피부 위에서 부드럽게 빛나며 인물의 내면과 정체성을 함께 드러내죠. 유년·청소년·성인 세 장으로 나뉜 이야기는 시기마다 색조와 질감을 미묘하게 달리해 한 사람의 변화를 색으로 기록합니다. 달빛 아래 해변 장면처럼, 색온도와 피부톤의 관계를 섬세하게 다루는 법을 배우기에 더없이 귀한 작품입니다.", en: "James Laxton's cinematography is a deep meditation on how to sculpt Black skin with light. Blue- and purple-tinted lighting glows softly on the skin, drawing out the character's inner life and identity at once. Told in three chapters of childhood, adolescence and adulthood, the film subtly shifts its tones and textures across each era, recording one person's change as colour. From the moonlit beach onward, it is a rare lesson in the delicate relationship between colour temperature and skin tone.", ja: "ジェームズ・ラクストンの撮影は、黒い肌をいかに光で彫るかを深く見つめた仕事です。青と紫を帯びた照明は肌の上で柔らかく輝き、人物の内面とアイデンティティを同時に浮かび上がらせます。少年期・思春期・成人期の三章に分かれた物語は、時期ごとに色調と質感を微妙に変え、一人の変化を色として記録します。月光の浜辺の場面のように、色温度と肌の色の関係を繊細に扱う術を学ぶ、得難い一作です。" },
    url: "https://www.themoviedb.org/movie/376867",
    image: "https://image.tmdb.org/t/p/w780/A9KPbYTQvWsp51Lgz85ukVkFrKf.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/A9KPbYTQvWsp51Lgz85ukVkFrKf.jpg", "https://image.tmdb.org/t/p/w780/2yfIUQYOpwxdivaYCuNiL2yr8h5.jpg", "https://image.tmdb.org/t/p/w780/v0qkC1c06zg2XsBmOb1S90JNiLg.jpg"],
    studio: "A24 · Plan B Entertainment",
  },
  {
    id: "carol",
    title: { ko: "캐롤", en: "Carol", ja: "キャロル" },
    credit: { ko: "토드 헤인즈 · 촬영 에드워드 라크만 · 2015", en: "Todd Haynes · DP Edward Lachman · 2015", ja: "トッド・ヘインズ · 撮影 エドワード・ラックマン · 2015" },
    lesson: { ko: "슈퍼 16mm의 입자감과 유리 너머의 시선을 배워보세요. 빗물 흐르는 창이 1950년대의 그리움을 한 겹 덧입힙니다.", en: "Learn Super 16 grain and the gaze through glass, where a rain-streaked window adds a layer of 1950s longing.", ja: "スーパー16mmの粒状感とガラス越しの視線を学べます。雨に濡れた窓が1950年代の憧れを一枚重ねます。" },
    curation: { ko: "헤인즈와 라크만은 슈퍼 16mm 필름의 부드러운 입자로 1950년대의 결을 되살립니다. 인물을 자주 창과 차창, 흐릿한 전경 너머에 두어, 관객조차 함부로 다가설 수 없는 절제된 그리움의 거리를 만듭니다. 빗물 흐르는 유리와 바랜 색조는 억눌린 감정을 가리는 동시에 더 사무치게 드러냅니다. 필름의 질감과 프레임 속 또 다른 프레임이 어떻게 감정의 거리를 조형하는지 배우기 좋은 작품입니다.", en: "Haynes and Lachman revive the texture of the 1950s through the soft grain of Super 16 film. Characters are often placed beyond windows, car glass and hazy foregrounds, building a restrained distance of longing that even the viewer cannot quite breach. Rain-streaked glass and faded tones at once conceal and more keenly expose suppressed feeling. It is a fine study in how film texture and frames-within-frames can sculpt emotional distance.", ja: "ヘインズとラックマンはスーパー16mmフィルムの柔らかな粒状感で1950年代の質感をよみがえらせます。人物をしばしば窓や車のガラス、ぼやけた前景の向こうに置き、観客さえうかつに近づけない抑制された憧れの距離を作ります。雨に濡れたガラスと褪せた色調が、抑え込まれた感情を隠すと同時に、いっそう切なく露わにします。フィルムの質感とフレームの中のフレームがいかに感情の距離を造形するかを学ぶのに良い一本です。" },
    url: "https://www.themoviedb.org/movie/258480",
    image: "https://image.tmdb.org/t/p/w780/cfEuvi63GWdLcNFwfxVBOXHX1i5.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/cfEuvi63GWdLcNFwfxVBOXHX1i5.jpg", "https://image.tmdb.org/t/p/w780/o0ghC4XMIMdbRBXIqSvnPrxwj3W.jpg", "https://image.tmdb.org/t/p/w780/qw8VxM1IrtB3zArAPKboNGWzvaf.jpg", "https://image.tmdb.org/t/p/w780/2giW19Qb8Lmyd5XCyVU2avABvhZ.jpg"],
    studio: "Killer Films · Number 9 Films",
  },
  {
    id: "her",
    title: { ko: "그녀", en: "Her", ja: "her／世界でひとつの彼女" },
    credit: { ko: "스파이크 존즈 · 촬영 호이트 반 호이테마 · 2013", en: "Dir. Spike Jonze · DP Hoyte van Hoytema · 2013", ja: "監督 スパイク・ジョーンズ · 撮影 ホイテ・ヴァン・ホイテマ · 2013" },
    lesson: { ko: "따뜻한 빨강과 코랄 톤으로 가까운 미래를 어떻게 포근하면서도 외롭게 그려내는지 배워 보세요. 부드러운 색이 친밀함과 고독을 동시에 말합니다.", en: "Learn how warm reds and corals paint a near future that feels cosy yet lonely. Soft colour speaks of intimacy and solitude in the same breath.", ja: "温かな赤やコーラルのトーンで、近未来をいかに居心地よく、しかし孤独に描くかを学べます。柔らかな色が親密さと孤独を同時に語ります。" },
    curation: { ko: "스파이크 존즈와 촬영감독 호이트 반 호이테마는 차갑게 그려지기 쉬운 미래를 빨강과 코랄, 포근한 파스텔로 채워, 기술에 둘러싸인 외로움을 역설적으로 다정하게 보여 줍니다. 인물에 바짝 붙은 얕은 심도와 부드러운 빛은 화면을 따뜻하게 감싸는 동시에, 그 온기 속 주인공의 고립을 더 또렷하게 만들죠. 흐릿한 배경의 도시는 사람들로 가득하지만 어딘가 텅 빈 듯한 정서를 자아냅니다. 색과 빛의 온도로 친밀함과 외로움을 함께 담아내는 법을 배우기에 좋은 작품입니다.", en: "Spike Jonze and cinematographer Hoyte van Hoytema fill a future that could easily look cold with reds, corals and gentle pastels, showing technology-wrapped loneliness with paradoxical tenderness. Shallow focus held close to the characters and soft light warm the image while making the protagonist's isolation, inside that warmth, all the sharper. The blurred city behind him teems with people yet feels somehow hollow. It's a fine study in carrying both intimacy and loneliness through the temperature of colour and light.", ja: "スパイク・ジョーンズと撮影監督ホイテ・ヴァン・ホイテマは、冷たく描かれがちな未来を赤やコーラル、柔らかなパステルで満たし、テクノロジーに囲まれた孤独を逆説的に優しく見せます。人物に寄った浅い被写界深度と柔らかい光が画面を温かく包む一方で、その温もりの中の主人公の孤立をいっそう際立たせます。ぼやけた背景の都市は人で溢れているのに、どこか空虚な情緒を漂わせます。色と光の温度で親密さと孤独をともに描く術を学ぶのに良い作品です。" },
    url: "https://www.themoviedb.org/movie/152601",
    image: "https://image.tmdb.org/t/p/w780/nG5zmbVeYlcDhckrPAe06fArywn.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/nG5zmbVeYlcDhckrPAe06fArywn.jpg", "https://image.tmdb.org/t/p/w780/1YnZchmaGc8dchgRPDpR1KGrixA.jpg", "https://image.tmdb.org/t/p/w780/pkAvtcRjk0oNzXmAY3ZcpsMSkbV.jpg", "https://image.tmdb.org/t/p/w780/zxttikp0SNEtF4vWsg70Vs6McFi.jpg"],
    studio: "Annapurna Pictures",
  },
  {
    id: "la-la-land",
    title: { ko: "라라랜드", en: "La La Land", ja: "ラ・ラ・ランド" },
    credit: { ko: "데이미언 셔젤 · 촬영 라이너스 산드그렌 · 2016", en: "Dir. Damien Chazelle · DP Linus Sandgren · 2016", ja: "監督 デイミアン・チャゼル · 撮影 リヌス・サンドグレン · 2016" },
    lesson: { ko: "선명한 원색 의상과 해 질 녘 로스앤젤레스의 빛에서, 색채와 자연광을 뮤지컬의 감정으로 끌어올리는 법을 배웁니다.", en: "Learn to lift colour and natural light into musical emotion from bold primary costumes and magic-hour Los Angeles.", ja: "鮮やかな原色の衣装と黄昏のロサンゼルスの光から、色彩と自然光をミュージカルの感情へ高める術を学びます。" },
    curation: { ko: "산드그렌은 노랑·파랑·빨강의 선명한 원색을 의상과 세트에 칠해, 고전 할리우드 뮤지컬의 발랄함을 현대 화면으로 되살립니다. 해 질 녘 로스앤젤레스의 보랏빛 하늘을 배경으로 두 사람이 춤추는 장면은 매직아워의 짧은 빛을 정교하게 붙잡은 결과입니다. 긴 호흡의 트래킹과 와이드 프레임은 노래와 안무를 끊지 않고 한 호흡으로 담아 무대의 생동감을 살립니다. 색과 빛, 카메라 움직임이 한데 어울려 감정을 고조시키는 방식을 배우기에 좋습니다.", en: "Sandgren paints costumes and sets in vivid primaries of yellow, blue and red, reviving the buoyancy of classic Hollywood musicals on a modern screen. The scene of two dancers against the violet sky of dusk over Los Angeles is the result of precisely catching the brief light of magic hour. Long, sustained tracking shots and wide framing hold song and choreography in a single breath without cutting, keeping the liveliness of the stage. It is a fine film for learning how colour, light and camera movement work together to heighten emotion.", ja: "サンドグレンは黄・青・赤の鮮やかな原色を衣装やセットに塗り、古典ハリウッド・ミュージカルの躍動を現代の画面に蘇らせます。黄昏のロサンゼルスの紫の空を背に二人が踊る場面は、マジックアワーの短い光を精緻に捉えた成果です。長い呼吸のトラッキングとワイドなフレームは、歌と振付を切らずに一息で収め、舞台の生き生きとした息づかいを保ちます。色と光、カメラの動きが一つに溶け合って感情を高める方法を学ぶのに最適です。" },
    url: "https://www.themoviedb.org/movie/313369",
    image: "https://image.tmdb.org/t/p/w780/2wmDyHz4gvF6m51IQZJnJzlLsnz.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/2wmDyHz4gvF6m51IQZJnJzlLsnz.jpg", "https://image.tmdb.org/t/p/w780/meGzYSwHzBWNQk9lYVNxdUrFqiC.jpg", "https://image.tmdb.org/t/p/w780/rVRtRE6HJ5xbdo5jd9aTT8tEVaF.jpg", "https://image.tmdb.org/t/p/w780/z830hvnEW6E7KyMSLRKm4HvJRhN.jpg"],
    studio: "Summit Entertainment · Gilbert Films",
  },
  {
    id: "portrait-of-a-lady-on-fire",
    title: { ko: "타오르는 여인의 초상", en: "Portrait of a Lady on Fire", ja: "燃ゆる女の肖像" },
    credit: { ko: "셀린 시아마 · 촬영 클레르 마통 · 2019", en: "Céline Sciamma · DP Claire Mathon · 2019", ja: "セリーヌ・シアマ · 撮影 クレール・マトン · 2019" },
    lesson: { ko: "회화처럼 다듬은 자연광 촬영을 배워보세요. 초와 벽난로, 낮의 빛만으로 인물을 그려내는 방식과 초록·빨강을 절제해 쓰는 색의 무게를 보여줍니다.", en: "Study painterly natural-light cinematography. Candles, firelight and daylight render the figures, while spare touches of green and red carry real weight.", ja: "絵画のように整えた自然光撮影を学べます。蝋燭や暖炉、昼の光だけで人物を描く手法と、緑や赤を抑えて使う色の重みがわかります。" },
    curation: { ko: "클레르 마통은 18세기 유화를 옮겨놓은 듯한 자연광으로 화면을 채웁니다. 촛불과 벽난로, 창으로 드는 낮의 빛만으로 인물의 피부와 옷의 질감을 그려내고, 드물게 등장하는 초록 드레스와 붉은 빛은 절제되어 더욱 강렬하게 박히죠. 보는 사람과 보이는 사람이 동등하게 마주 보는 여성의 시선 속에서, 카메라는 응시 그 자체를 사랑의 언어로 만듭니다. 빛과 색을 회화의 언어로 다루는 법을 배우기에 가장 아름다운 교본 중 하나입니다.", en: "Claire Mathon fills the frame with natural light that feels lifted from an 18th-century oil painting. Candles, firelight and daylight through a window render skin and fabric, while the rare green dress or flash of red lands harder for being so restrained. Within a female gaze where watcher and watched meet as equals, the camera turns looking itself into a language of love. It is one of the most beautiful primers on handling light and colour like a painter.", ja: "クレール・マトンは、18世紀の油彩画から抜き出したような自然光で画面を満たします。蝋燭や暖炉、窓から差す昼の光だけで肌や布の質感を描き、まれに現れる緑のドレスや赤の輝きは抑制ゆえにいっそう強く焼きつきます。見る者と見られる者が対等に向き合う女性のまなざしの中で、カメラは凝視そのものを愛の言葉に変えます。光と色を絵画の言語として扱う術を学ぶ、最も美しい手本の一つです。" },
    url: "https://www.themoviedb.org/movie/531428",
    image: "https://image.tmdb.org/t/p/w780/xhuGwXvm5o2G9ms9YxP23NXjbl7.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/xhuGwXvm5o2G9ms9YxP23NXjbl7.jpg", "https://image.tmdb.org/t/p/w780/foFq1RZWQIgFuCQ0nyYccywjFyX.jpg", "https://image.tmdb.org/t/p/w780/ivJ5UzT6IzucLVfbZwCCwiJJoBz.jpg", "https://image.tmdb.org/t/p/w780/bjXr3VbTj8tgTCCgh5QYd5C5clD.jpg"],
    studio: "Lilies Films · ARTE France Cinéma",
  },
  {
    id: "drive",
    title: { ko: "드라이브", en: "Drive", ja: "ドライヴ" },
    credit: { ko: "니콜라스 빈딩 레픈 · 촬영 뉴턴 토머스 시겔 · 2011", en: "Nicolas Winding Refn · DP Newton Thomas Sigel · 2011", ja: "ニコラス・ウィンディング・レフン · 撮影 ニュートン・トーマス・サイジェル · 2011" },
    lesson: { ko: "네온이 번지는 로스앤젤레스의 밤을 배워보세요. 마젠타와 시안의 인공조명이 침묵하는 인물에 차가운 낭만을 입힙니다.", en: "Learn the neon Los Angeles night, where magenta and cyan light wrap a silent figure in cold romance.", ja: "ネオンがにじむロサンゼルスの夜を学べます。マゼンタとシアンの人工光が寡黙な人物に冷たいロマンをまといます。" },
    curation: { ko: "레픈과 시겔은 로스앤젤레스의 밤을 마젠타와 시안의 네온으로 칠해, 폭력적이면서도 몽환적인 낭만을 만들어냅니다. 인공조명을 적극적으로 끌어들인 색대비는 말 없는 주인공의 내면을 색으로 대신 말하고, 새틴 재킷의 전갈은 그 차가운 도시 위 유일한 표식처럼 빛납니다. 절제된 카메라와 과감한 색은 침묵과 폭발을 오가는 리듬을 만듭니다. 색조와 인공조명만으로 분위기와 캐릭터를 동시에 세우는 법을 보여주는 작품입니다.", en: "Refn and Sigel paint the Los Angeles night in magenta and cyan neon, conjuring a romance that is at once violent and dreamlike. Colour contrasts built from embraced artificial light speak for the silent protagonist's interior, while the scorpion on his satin jacket gleams like the one mark over that cold city. A restrained camera paired with bold colour creates a rhythm that swings between silence and eruption. It shows how tone and artificial light alone can establish mood and character at the same time.", ja: "レフンとサイジェルはロサンゼルスの夜をマゼンタとシアンのネオンで塗り、暴力的でありながら夢幻的なロマンを生み出します。人工光を積極的に取り込んだ色対比が寡黙な主人公の内面を色で代弁し、サテンのジャケットのサソリは冷たい都市の上の唯一の印のように輝きます。抑制されたカメラと大胆な色が、沈黙と爆発を行き来するリズムを作ります。色調と人工光だけで雰囲気とキャラクターを同時に立ち上げる術を示す一本です。" },
    url: "https://www.themoviedb.org/movie/64690",
    image: "https://image.tmdb.org/t/p/w780/oeEiUwvqHxWT0XqD3YlViaiJOVD.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/oeEiUwvqHxWT0XqD3YlViaiJOVD.jpg", "https://image.tmdb.org/t/p/w780/1oaLxMtdn47TWdaty8BwdU4oXhV.jpg", "https://image.tmdb.org/t/p/w780/vMG0UBz12zaQC19snnq5vjvAJ8t.jpg", "https://image.tmdb.org/t/p/w780/iymDDg4upZWgpbSeiE1JCjsSPBs.jpg"],
    studio: "FilmDistrict · Bold Films",
  },
  {
    id: "roma",
    title: { ko: "로마", en: "Roma", ja: "ROMA／ローマ" },
    credit: { ko: "알폰소 쿠아론 · 촬영 알폰소 쿠아론 · 2018", en: "Dir. Alfonso Cuarón · DP Alfonso Cuarón · 2018", ja: "監督 アルフォンソ・キュアロン · 撮影 アルフォンソ・キュアロン · 2018" },
    lesson: { ko: "흑백의 깊은 심도와 천천히 옆으로 미끄러지는 카메라로, 어떻게 기억의 결을 화면에 담는지 배워 보세요. 빛과 회색조만으로도 풍부한 깊이가 만들어집니다.", en: "Learn how black-and-white deep focus and slow lateral pans capture the texture of memory. Light and shades of grey alone can build rich depth.", ja: "モノクロの深い被写界深度と、ゆっくり横へ滑るカメラで、いかに記憶の手触りを画面に収めるかを学べます。光とグレースケールだけで豊かな奥行きが生まれます。" },
    curation: { ko: "감독이자 촬영까지 맡은 알폰소 쿠아론은 1970년대 멕시코시티의 기억을 흑백 디지털 화면에 깊은 심도로 새겨, 전경의 인물부터 먼 배경의 거리까지 또렷이 살아 숨 쉬게 합니다. 카메라는 서두르지 않고 좌우로 천천히 미끄러지며, 한 가족과 가정부의 일상을 마치 기억이 풍경을 훑듯 응시하죠. 색을 덜어낸 화면은 빛과 질감, 디테일에 더 집중하게 만들어, 일상의 작은 순간들에 묵직한 무게를 부여합니다. 흑백과 깊은 심도, 느린 움직임으로 기억과 시간을 영상화하는 법을 배우기에 더없이 풍요로운 작품입니다.", en: "Serving as both director and cinematographer, Alfonso Cuarón etches his memories of 1970s Mexico City onto a black-and-white digital frame with deep focus, keeping everything — from figures in the foreground to streets far behind — vividly alive. The camera never hurries, gliding slowly side to side as it watches the daily life of a family and their housekeeper, the way memory sweeps across a landscape. Stripped of colour, the image draws attention to light, texture and detail, lending grave weight to small everyday moments. It's a richly rewarding study in turning memory and time into image through black-and-white, deep focus and slow movement.", ja: "監督と撮影を兼ねたアルフォンソ・キュアロンは、1970年代メキシコシティの記憶をモノクロのデジタル画面に深い被写界深度で刻み、前景の人物から遠い背景の街並みまで鮮明に息づかせます。カメラは急がず左右へゆっくり滑り、ある一家と家政婦の日常を、まるで記憶が風景を撫でるように見つめます。色を削ぎ落とした画面は光や質感、ディテールへ意識を集め、日常の小さな瞬間に重い厚みを与えます。モノクロと深い被写界深度、ゆるやかな動きで記憶と時間を映像化する術を学ぶのに、この上なく豊かな作品です。" },
    url: "https://www.themoviedb.org/movie/426426",
    image: "https://image.tmdb.org/t/p/w780/zl9uqCl5iUSb50sTk2BPzw6bJnU.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/zl9uqCl5iUSb50sTk2BPzw6bJnU.jpg", "https://image.tmdb.org/t/p/w780/uXs8rTXZDaWUclprxZuxfaZqei5.jpg", "https://image.tmdb.org/t/p/w780/xqFPJFZoukpe598gNIh4W6c7lBC.jpg", "https://image.tmdb.org/t/p/w780/1KlrtbqRt17HoQNLCxUMFAAcT8I.jpg"],
    studio: "Participant · Esperanto Filmoj",
  },
  {
    id: "mad-max-fury-road",
    title: { ko: "매드맥스: 분노의 도로", en: "Mad Max: Fury Road", ja: "マッドマックス 怒りのデス・ロード" },
    credit: { ko: "조지 밀러 · 촬영 존 실 · 2015", en: "Dir. George Miller · DP John Seale · 2015", ja: "監督 ジョージ・ミラー · 撮影 ジョン・シール · 2015" },
    lesson: { ko: "낮은 주황, 밤은 파랑으로 가른 색 대비와 중앙 정렬 구도에서, 빠른 액션에서도 시선을 놓치지 않게 하는 법을 배웁니다.", en: "Learn to hold the eye through fast action from orange days and blue nights and relentless centre framing.", ja: "昼は橙、夜は青で分けた色対比と中央配置の構図から、激しいアクションでも視線を逃さない術を学びます。" },
    curation: { ko: "밀러와 실은 사막의 낮을 강렬한 주황으로, 밤을 차가운 파랑으로 채색해 시간과 위협의 온도를 색으로 명확히 가릅니다. 핵심 정보를 늘 화면 정중앙에 두는 센터 프레이밍 덕에, 초당 컷이 쏟아지는 추격전에서도 관객의 눈은 한순간도 길을 잃지 않습니다. 빠른 액션은 약간의 고속 프레임 조정으로 가독성을 확보해, 혼돈 속에서도 동작이 또렷이 읽히도록 설계되었습니다. 컬러 대비와 구도만으로 속도와 명료함을 동시에 잡는 액션 촬영의 정수를 보여 줍니다.", en: "Miller and Seale colour the desert day in fierce orange and the night in cold blue, drawing a clear line between the temperatures of time and threat through hue. Thanks to centre framing that keeps key information dead-centre at all times, the viewer's eye never loses its way even in a chase that pours out cuts by the second. The fast action secures legibility through slight frame-rate adjustment, engineered so that movement reads clearly even amid chaos. It shows the essence of action cinematography that catches speed and clarity at once through colour contrast and composition alone.", ja: "ミラーとシールは砂漠の昼を強烈な橙に、夜を冷たい青に彩色し、時間と脅威の温度を色で明確に分けます。重要な情報を常に画面の中央に置くセンター・フレーミングのおかげで、毎秒コマが降り注ぐ追走劇でも観客の目は一瞬たりとも道に迷いません。速いアクションはわずかな高速フレーム調整で可読性を確保し、混沌の中でも動きがくっきり読めるよう設計されています。色の対比と構図だけで速度と明瞭さを同時に掴む、アクション撮影の精髄を見せてくれます。" },
    url: "https://www.themoviedb.org/movie/76341",
    image: "https://image.tmdb.org/t/p/w780/8yACFuo4OaIiKr9hHFlmPcGalKx.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/8yACFuo4OaIiKr9hHFlmPcGalKx.jpg", "https://image.tmdb.org/t/p/w780/n6vWE0bXq4ImAM00iM5gWyORNSM.jpg", "https://image.tmdb.org/t/p/w780/c8WmTUONXBPKkKzx1emy7t0i7zX.jpg"],
    studio: "Warner Bros. Pictures · Village Roadshow Pictures",
  },
  {
    id: "pans-labyrinth",
    title: { ko: "판의 미로", en: "Pan's Labyrinth", ja: "パンズ・ラビリンス" },
    credit: { ko: "기예르모 델 토로 · 촬영 기예르모 나바로 · 2006", en: "Guillermo del Toro · DP Guillermo Navarro · 2006", ja: "ギレルモ・デル・トロ · 撮影 ギレルモ・ナバロ · 2006" },
    lesson: { ko: "두 세계를 색으로 나누는 연출을 배워보세요. 따뜻한 금빛의 환상과 차가운 푸른빛의 현실을 색온도로 대비시켜 이야기를 시각적으로 갈라놓는 법을 보여줍니다.", en: "Learn to split two worlds by colour. Warm gold for fantasy against cold blue for reality divides the story through colour temperature alone.", ja: "二つの世界を色で分ける演出を学べます。温かい金色の幻想と冷たい青の現実を色温度で対比させ、物語を視覚的に分かつ手法がわかります。" },
    curation: { ko: "기예르모 나바로는 색온도로 두 세계를 또렷이 갈라놓습니다. 소녀가 발 디딘 환상의 미로는 따뜻한 황금빛으로, 전쟁이 짓누르는 현실은 차갑고 푸른빛으로 칠해져 같은 화면 안에서도 두 세계의 정서가 분명히 구분되죠. 동화의 빛과 잔혹한 현실의 그림자가 한 영화 안에 공존하며 기묘하고 슬픈 아름다움을 빚어냅니다. 색의 온도만으로 서로 다른 현실을 설계하는 법을 배우기에 더없이 명료한 작품입니다.", en: "Guillermo Navarro splits two worlds cleanly through colour temperature. The fantastical labyrinth the girl steps into glows warm and gold, while the war-crushed reality is painted cold and blue, so the two worlds stay emotionally distinct even within one frame. Fairy-tale light and the shadows of brutal history coexist in a single film, conjuring a strange, sorrowful beauty. As a study in designing separate realities through the temperature of colour alone, it could hardly be clearer.", ja: "ギレルモ・ナバロは色温度で二つの世界をはっきりと分けます。少女が踏み込む幻想の迷宮は温かな金色で、戦争が押し潰す現実は冷たく青い光で塗られ、同じ画面の中でも二つの世界の情緒が明確に区別されます。おとぎ話の光と残酷な現実の影が一本の映画に共存し、奇妙で悲しい美しさを生み出します。色の温度だけで異なる現実を設計する術を学ぶ、この上なく明快な一作です。" },
    url: "https://www.themoviedb.org/movie/1417",
    image: "https://image.tmdb.org/t/p/w780/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg",
    gallery: ["https://image.tmdb.org/t/p/w780/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg", "https://image.tmdb.org/t/p/w780/o0IWa75BXyXryNDVqw0xoXZzy1J.jpg", "https://image.tmdb.org/t/p/w780/5aSL5snrPUkOmMPFtblMNrihz1P.jpg", "https://image.tmdb.org/t/p/w780/A0olyqHodbhmClULDd5zBJmfXxq.jpg"],
    studio: "Estudios Picasso · Esperanto Filmoj",
  },
];

export const CINEMA_ALL: CinemaScene[] = [...CINEMA_MODERN, ...CINEMA_PD];

export function cinemaById(id: string): CinemaScene | undefined {
  return CINEMA_ALL.find((s) => s.id === id);
}

export function cinemaIds(): string[] {
  return CINEMA_ALL.map((s) => s.id);
}
